/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type SteamUgcQuery = SteamUGCQuery;

declare enum SteamUGCQuery {
    RankedByVote = 0,
    RankedByPublicationDate = 1,
    AcceptedForGameRankedByAcceptanceDate = 2,
    RankedByTrend = 3,
    FavoritedByFriendsRankedByPublicationDate = 4,
    CreatedByFriendsRankedByPublicationDate = 5,
    RankedByNumTimesReported = 6,
    CreatedByFollowedUsersRankedByPublicationDate = 7,
    NotYetRated = 8,
    RankedByTotalVotesAsc = 9,
    RankedByVotesUp = 10,
    RankedByTextSearch = 11,
    RankedByTotalUniqueSubscriptions = 12,
    RankedByPlaytimeTrend = 13,
    RankedByTotalPlaytime = 14,
    RankedByAveragePlaytimeTrend = 15,
    RankedByLifetimeAveragePlaytime = 16,
    RankedByPlaytimeSessionsTrend = 17,
    RankedByLifetimePlaytimeSessions = 18,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type SteamUgcMatchingUgcType = SteamUGCMatchingUGCType;

declare enum SteamUGCMatchingUGCType {
    Items = 0,
    Items_Mtx = 1,
    Items_ReadyToUse = 2,
    Collections = 3,
    Artwork = 4,
    Videos = 5,
    Screenshots = 6,
    AllGuides = 7,
    WebGuides = 8,
    IntegratedGuides = 9,
    UsableInGame = 10,
    ControllerBindings = 11,
    GameManagedItems = 12,
    All = -1,
}

declare enum SteamUniverse {
    Invalid = 0,
    Internal = 3,
    Dev = 4,
    Beta = 2,
    Public = 1,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type GameState = DOTA_GameState;

declare enum DOTA_GameState {
    DOTA_GAMERULES_STATE_INIT = 0,
    DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1,
    DOTA_GAMERULES_STATE_HERO_SELECTION = 4,
    DOTA_GAMERULES_STATE_STRATEGY_TIME = 5,
    DOTA_GAMERULES_STATE_PRE_GAME = 8,
    DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 10,
    DOTA_GAMERULES_STATE_POST_GAME = 11,
    DOTA_GAMERULES_STATE_DISCONNECT = 12,
    DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 6,
    DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2,
    DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 7,
    DOTA_GAMERULES_STATE_SCENARIO_SETUP = 9,
    DOTA_GAMERULES_STATE_PLAYER_DRAFT = 3,
    DOTA_GAMERULES_STATE_LAST = 0,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type GcTeam = DOTA_GC_TEAM;

declare enum DOTA_GC_TEAM {
    DOTA_GC_TEAM_GOOD_GUYS = 0,
    DOTA_GC_TEAM_BAD_GUYS = 1,
    DOTA_GC_TEAM_BROADCASTER = 2,
    DOTA_GC_TEAM_SPECTATOR = 3,
    DOTA_GC_TEAM_PLAYER_POOL = 4,
    DOTA_GC_TEAM_NOTEAM = 5,
    DOTA_GC_TEAM_CUSTOM_1 = 6,
    DOTA_GC_TEAM_CUSTOM_2 = 7,
    DOTA_GC_TEAM_CUSTOM_3 = 8,
    DOTA_GC_TEAM_CUSTOM_4 = 9,
    DOTA_GC_TEAM_CUSTOM_5 = 10,
    DOTA_GC_TEAM_CUSTOM_6 = 11,
    DOTA_GC_TEAM_CUSTOM_7 = 12,
    DOTA_GC_TEAM_CUSTOM_8 = 13,
    DOTA_GC_TEAM_NEUTRALS = 14,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type GameMode = DOTA_GameMode;

declare enum DOTA_GameMode {
    DOTA_GAMEMODE_NONE = 0,
    DOTA_GAMEMODE_AP = 1,
    DOTA_GAMEMODE_CM = 2,
    DOTA_GAMEMODE_RD = 3,
    DOTA_GAMEMODE_SD = 4,
    DOTA_GAMEMODE_AR = 5,
    DOTA_GAMEMODE_INTRO = 6,
    DOTA_GAMEMODE_HW = 7,
    DOTA_GAMEMODE_REVERSE_CM = 8,
    DOTA_GAMEMODE_XMAS = 9,
    DOTA_GAMEMODE_TUTORIAL = 10,
    DOTA_GAMEMODE_MO = 11,
    DOTA_GAMEMODE_LP = 12,
    DOTA_GAMEMODE_POOL1 = 13,
    DOTA_GAMEMODE_FH = 14,
    DOTA_GAMEMODE_CUSTOM = 15,
    DOTA_GAMEMODE_CD = 16,
    DOTA_GAMEMODE_BD = 17,
    DOTA_GAMEMODE_ABILITY_DRAFT = 18,
    DOTA_GAMEMODE_EVENT = 19,
    DOTA_GAMEMODE_ARDM = 20,
    DOTA_GAMEMODE_1V1MID = 21,
    DOTA_GAMEMODE_ALL_DRAFT = 22,
    DOTA_GAMEMODE_TURBO = 23,
    DOTA_GAMEMODE_MUTATION = 24,
    DOTA_GAMEMODE_COACHES_CHALLENGE = 25,
    DOTA_GAMEMODE_BOT_CHALLENGE = 26,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ConnectionState = DOTAConnectionState_t;

declare enum DOTAConnectionState_t {
    DOTA_CONNECTION_STATE_UNKNOWN = 0,
    DOTA_CONNECTION_STATE_NOT_YET_CONNECTED = 1,
    DOTA_CONNECTION_STATE_CONNECTED = 2,
    DOTA_CONNECTION_STATE_DISCONNECTED = 3,
    DOTA_CONNECTION_STATE_ABANDONED = 4,
    DOTA_CONNECTION_STATE_LOADING = 5,
    DOTA_CONNECTION_STATE_FAILED = 6,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitOrder = dotaunitorder_t;

declare enum dotaunitorder_t {
    DOTA_UNIT_ORDER_NONE = 0,
    DOTA_UNIT_ORDER_MOVE_TO_POSITION = 1,
    DOTA_UNIT_ORDER_MOVE_TO_TARGET = 2,
    DOTA_UNIT_ORDER_ATTACK_MOVE = 3,
    DOTA_UNIT_ORDER_ATTACK_TARGET = 4,
    DOTA_UNIT_ORDER_CAST_POSITION = 5,
    DOTA_UNIT_ORDER_CAST_TARGET = 6,
    DOTA_UNIT_ORDER_CAST_TARGET_TREE = 7,
    DOTA_UNIT_ORDER_CAST_NO_TARGET = 8,
    DOTA_UNIT_ORDER_CAST_TOGGLE = 9,
    DOTA_UNIT_ORDER_HOLD_POSITION = 10,
    DOTA_UNIT_ORDER_TRAIN_ABILITY = 11,
    DOTA_UNIT_ORDER_DROP_ITEM = 12,
    DOTA_UNIT_ORDER_GIVE_ITEM = 13,
    DOTA_UNIT_ORDER_PICKUP_ITEM = 14,
    DOTA_UNIT_ORDER_PICKUP_RUNE = 15,
    DOTA_UNIT_ORDER_PURCHASE_ITEM = 16,
    DOTA_UNIT_ORDER_SELL_ITEM = 17,
    DOTA_UNIT_ORDER_DISASSEMBLE_ITEM = 18,
    DOTA_UNIT_ORDER_MOVE_ITEM = 19,
    DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO = 20,
    DOTA_UNIT_ORDER_STOP = 21,
    DOTA_UNIT_ORDER_TAUNT = 22,
    DOTA_UNIT_ORDER_BUYBACK = 23,
    DOTA_UNIT_ORDER_GLYPH = 24,
    DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH = 25,
    DOTA_UNIT_ORDER_CAST_RUNE = 26,
    DOTA_UNIT_ORDER_PING_ABILITY = 27,
    DOTA_UNIT_ORDER_MOVE_TO_DIRECTION = 28,
    DOTA_UNIT_ORDER_PATROL = 29,
    DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION = 30,
    DOTA_UNIT_ORDER_RADAR = 31,
    DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK = 32,
    DOTA_UNIT_ORDER_CONTINUE = 33,
    DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED = 34,
    DOTA_UNIT_ORDER_CAST_RIVER_PAINT = 35,
    DOTA_UNIT_ORDER_PREGAME_ADJUST_ITEM_ASSIGNMENT = 36,
    DOTA_UNIT_ORDER_DROP_ITEM_AT_FOUNTAIN = 37,
    DOTA_UNIT_ORDER_TAKE_ITEM_FROM_NEUTRAL_ITEM_STASH = 38,
    DOTA_UNIT_ORDER_MOVE_RELATIVE = 39,
    DOTA_UNIT_ORDER_CAST_TOGGLE_ALT = 40,
    DOTA_UNIT_ORDER_CONSUME_ITEM = 41,
    DOTA_UNIT_ORDER_SET_ITEM_MARK_FOR_SELL = 42,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type OverheadAlert = DOTA_OVERHEAD_ALERT;

declare enum DOTA_OVERHEAD_ALERT {
    OVERHEAD_ALERT_GOLD = 0,
    OVERHEAD_ALERT_DENY = 1,
    OVERHEAD_ALERT_CRITICAL = 2,
    OVERHEAD_ALERT_XP = 3,
    OVERHEAD_ALERT_BONUS_SPELL_DAMAGE = 4,
    OVERHEAD_ALERT_MISS = 5,
    OVERHEAD_ALERT_DAMAGE = 6,
    OVERHEAD_ALERT_EVADE = 7,
    OVERHEAD_ALERT_BLOCK = 8,
    OVERHEAD_ALERT_BONUS_POISON_DAMAGE = 9,
    OVERHEAD_ALERT_HEAL = 10,
    OVERHEAD_ALERT_MANA_ADD = 11,
    OVERHEAD_ALERT_MANA_LOSS = 12,
    OVERHEAD_ALERT_MAGICAL_BLOCK = 16,
    OVERHEAD_ALERT_INCOMING_DAMAGE = 17,
    OVERHEAD_ALERT_OUTGOING_DAMAGE = 18,
    OVERHEAD_ALERT_DISABLE_RESIST = 19,
    OVERHEAD_ALERT_DEATH = 20,
    OVERHEAD_ALERT_BLOCKED = 21,
    OVERHEAD_ALERT_ITEM_RECEIVED = 22,
    OVERHEAD_ALERT_SHARD = 23,
    OVERHEAD_ALERT_DEADLY_BLOW = 24,
    OVERHEAD_ALERT_FORCE_MISS = 25,
    OVERHEAD_ALERT_AEGIS = 26,
    OVERHEAD_ALERT_DISPEL = 27,
    OVERHEAD_ALERT_BONUS_PURE_DAMAGE = 28,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type HeroPickState = DOTA_HeroPickState;

declare enum DOTA_HeroPickState {
    DOTA_HEROPICK_STATE_NONE = 0,
    DOTA_HEROPICK_STATE_AP_SELECT = 1,
    DOTA_HEROPICK_STATE_SD_SELECT = 2,
    DOTA_HEROPICK_STATE_INTRO_SELECT_UNUSED = 3,
    DOTA_HEROPICK_STATE_RD_SELECT_UNUSED = 4,
    DOTA_HEROPICK_STATE_CM_INTRO = 5,
    DOTA_HEROPICK_STATE_CM_CAPTAINPICK = 6,
    DOTA_HEROPICK_STATE_CM_BAN1 = 7,
    DOTA_HEROPICK_STATE_CM_BAN2 = 8,
    DOTA_HEROPICK_STATE_CM_BAN3 = 9,
    DOTA_HEROPICK_STATE_CM_BAN4 = 10,
    DOTA_HEROPICK_STATE_CM_BAN5 = 11,
    DOTA_HEROPICK_STATE_CM_BAN6 = 12,
    DOTA_HEROPICK_STATE_CM_BAN7 = 13,
    DOTA_HEROPICK_STATE_CM_BAN8 = 14,
    DOTA_HEROPICK_STATE_CM_BAN9 = 15,
    DOTA_HEROPICK_STATE_CM_BAN10 = 16,
    DOTA_HEROPICK_STATE_CM_BAN11 = 17,
    DOTA_HEROPICK_STATE_CM_BAN12 = 18,
    DOTA_HEROPICK_STATE_CM_BAN13 = 19,
    DOTA_HEROPICK_STATE_CM_BAN14 = 20,
    DOTA_HEROPICK_STATE_CM_SELECT1 = 21,
    DOTA_HEROPICK_STATE_CM_SELECT2 = 22,
    DOTA_HEROPICK_STATE_CM_SELECT3 = 23,
    DOTA_HEROPICK_STATE_CM_SELECT4 = 24,
    DOTA_HEROPICK_STATE_CM_SELECT5 = 25,
    DOTA_HEROPICK_STATE_CM_SELECT6 = 26,
    DOTA_HEROPICK_STATE_CM_SELECT7 = 27,
    DOTA_HEROPICK_STATE_CM_SELECT8 = 28,
    DOTA_HEROPICK_STATE_CM_SELECT9 = 29,
    DOTA_HEROPICK_STATE_CM_SELECT10 = 30,
    DOTA_HEROPICK_STATE_CM_PICK = 31,
    DOTA_HEROPICK_STATE_AR_SELECT = 32,
    DOTA_HEROPICK_STATE_MO_SELECT = 33,
    DOTA_HEROPICK_STATE_FH_SELECT = 34,
    DOTA_HEROPICK_STATE_CD_INTRO = 35,
    DOTA_HEROPICK_STATE_CD_CAPTAINPICK = 36,
    DOTA_HEROPICK_STATE_CD_BAN1 = 37,
    DOTA_HEROPICK_STATE_CD_BAN2 = 38,
    DOTA_HEROPICK_STATE_CD_BAN3 = 39,
    DOTA_HEROPICK_STATE_CD_BAN4 = 40,
    DOTA_HEROPICK_STATE_CD_BAN5 = 41,
    DOTA_HEROPICK_STATE_CD_BAN6 = 42,
    DOTA_HEROPICK_STATE_CD_SELECT1 = 43,
    DOTA_HEROPICK_STATE_CD_SELECT2 = 44,
    DOTA_HEROPICK_STATE_CD_SELECT3 = 45,
    DOTA_HEROPICK_STATE_CD_SELECT4 = 46,
    DOTA_HEROPICK_STATE_CD_SELECT5 = 47,
    DOTA_HEROPICK_STATE_CD_SELECT6 = 48,
    DOTA_HEROPICK_STATE_CD_SELECT7 = 49,
    DOTA_HEROPICK_STATE_CD_SELECT8 = 50,
    DOTA_HEROPICK_STATE_CD_SELECT9 = 51,
    DOTA_HEROPICK_STATE_CD_SELECT10 = 52,
    DOTA_HEROPICK_STATE_CD_PICK = 53,
    DOTA_HEROPICK_STATE_BD_SELECT = 54,
    DOTA_HERO_PICK_STATE_ABILITY_DRAFT_SELECT = 55,
    DOTA_HERO_PICK_STATE_ARDM_SELECT = 56,
    DOTA_HEROPICK_STATE_ALL_DRAFT_SELECT = 57,
    DOTA_HERO_PICK_STATE_CUSTOMGAME_SELECT = 58,
    DOTA_HEROPICK_STATE_SELECT_PENALTY = 59,
    DOTA_HEROPICK_STATE_CUSTOM_PICK_RULES = 60,
    DOTA_HEROPICK_STATE_SCENARIO_PICK = 61,
    DOTA_HEROPICK_STATE_COUNT = 62,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type DotaTeam = DOTATeam_t;

declare enum DOTATeam_t {
    DOTA_TEAM_FIRST = 2,
    DOTA_TEAM_GOODGUYS = 2,
    DOTA_TEAM_BADGUYS = 3,
    DOTA_TEAM_NEUTRALS = 4,
    DOTA_TEAM_NOTEAM = 5,
    DOTA_TEAM_CUSTOM_1 = 6,
    DOTA_TEAM_CUSTOM_2 = 7,
    DOTA_TEAM_CUSTOM_3 = 8,
    DOTA_TEAM_CUSTOM_4 = 9,
    DOTA_TEAM_CUSTOM_5 = 10,
    DOTA_TEAM_CUSTOM_6 = 11,
    DOTA_TEAM_CUSTOM_7 = 12,
    DOTA_TEAM_CUSTOM_8 = 13,
    DOTA_TEAM_DRAFT_POOL = 14,
    DOTA_TEAM_COUNT = 15,
    DOTA_TEAM_CUSTOM_MIN = 6,
    DOTA_TEAM_CUSTOM_MAX = 13,
    DOTA_TEAM_CUSTOM_COUNT = 8,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type RuneType = DOTA_RUNES;

declare enum DOTA_RUNES {
    DOTA_RUNE_INVALID = -1,
    DOTA_RUNE_DOUBLEDAMAGE = 0,
    DOTA_RUNE_HASTE = 1,
    DOTA_RUNE_ILLUSION = 2,
    DOTA_RUNE_INVISIBILITY = 3,
    DOTA_RUNE_REGENERATION = 4,
    DOTA_RUNE_BOUNTY = 5,
    DOTA_RUNE_ARCANE = 6,
    DOTA_RUNE_WATER = 7,
    DOTA_RUNE_XP = 8,
    DOTA_RUNE_SHIELD = 9,
    DOTA_RUNE_COUNT = 10,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitTargetTeam = DOTA_UNIT_TARGET_TEAM;

declare enum DOTA_UNIT_TARGET_TEAM {
    DOTA_UNIT_TARGET_TEAM_NONE = 0,
    DOTA_UNIT_TARGET_TEAM_FRIENDLY = 1,
    DOTA_UNIT_TARGET_TEAM_ENEMY = 2,
    DOTA_UNIT_TARGET_TEAM_CUSTOM = 4,
    DOTA_UNIT_TARGET_TEAM_BOTH = 3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitTargetType = DOTA_UNIT_TARGET_TYPE;

declare enum DOTA_UNIT_TARGET_TYPE {
    DOTA_UNIT_TARGET_NONE = 0,
    DOTA_UNIT_TARGET_HERO = 1,
    DOTA_UNIT_TARGET_CREEP = 2,
    DOTA_UNIT_TARGET_BUILDING = 4,
    DOTA_UNIT_TARGET_COURIER = 16,
    DOTA_UNIT_TARGET_OTHER = 32,
    DOTA_UNIT_TARGET_TREE = 64,
    DOTA_UNIT_TARGET_CUSTOM = 128,
    DOTA_UNIT_TARGET_SELF = 256,
    DOTA_UNIT_TARGET_BASIC = 18,
    DOTA_UNIT_TARGET_ALL = 55,
    DOTA_UNIT_TARGET_HEROES_AND_CREEPS = 19,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitTargetFlags = DOTA_UNIT_TARGET_FLAGS;

declare enum DOTA_UNIT_TARGET_FLAGS {
    DOTA_UNIT_TARGET_FLAG_NONE = 0,
    DOTA_UNIT_TARGET_FLAG_RANGED_ONLY = 2,
    DOTA_UNIT_TARGET_FLAG_MELEE_ONLY = 4,
    DOTA_UNIT_TARGET_FLAG_DEAD = 8,
    DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES = 16,
    DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES = 32,
    DOTA_UNIT_TARGET_FLAG_INVULNERABLE = 64,
    DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE = 128,
    DOTA_UNIT_TARGET_FLAG_NO_INVIS = 256,
    DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS = 512,
    DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED = 1024,
    DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED = 2048,
    DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED = 4096,
    DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS = 8192,
    DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE = 16384,
    DOTA_UNIT_TARGET_FLAG_MANA_ONLY = 32768,
    DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP = 65536,
    DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO = 131072,
    DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD = 262144,
    DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED = 524288,
    DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES = 1048576,
    DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS = 2097152,
    DOTA_UNIT_TARGET_FLAG_CAN_BE_SEEN = 384,
}

declare enum DOTALimits_t {
    /**
     * Max number of players connected to the server including spectators.
     */ DOTA_MAX_PLAYERS = 64,
    /**
     * Max number of players per team.
     */
    DOTA_MAX_TEAM = 24,
    /**
     * Max number of player teams supported.
     */
    DOTA_MAX_PLAYER_TEAMS = 10,
    /**
     * Max number of non-spectator players supported.
     */
    DOTA_MAX_TEAM_PLAYERS = 24,
    /**
     * How many spectators can watch.
     */
    DOTA_MAX_SPECTATOR_TEAM_SIZE = 40,
    /**
     * Max number of viewers in a spectator lobby.
     */
    DOTA_MAX_SPECTATOR_LOBBY_SIZE = 15,
    /**
     * Default number of players per team.
     */
    DOTA_DEFAULT_MAX_TEAM = 5,
    /**
     * Default number of non-spectator players supported.
     */
    DOTA_DEFAULT_MAX_TEAM_PLAYERS = 10,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type InventoryFlags = DOTAInventoryFlags_t;

declare enum DOTAInventoryFlags_t {
    DOTA_INVENTORY_ALLOW_NONE = 0,
    DOTA_INVENTORY_ALLOW_MAIN = 1,
    DOTA_INVENTORY_ALLOW_STASH = 2,
    DOTA_INVENTORY_ALLOW_DROP_ON_GROUND = 4,
    DOTA_INVENTORY_ALLOW_DROP_AT_FOUNTAIN = 8,
    DOTA_INVENTORY_LIMIT_DROP_ON_GROUND = 16,
    DOTA_INVENTORY_ALL_ACCESS = 3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ModifyGoldReason = EDOTA_ModifyGold_Reason;

declare enum EDOTA_ModifyGold_Reason {
    DOTA_ModifyGold_Unspecified = 0,
    DOTA_ModifyGold_Death = 1,
    DOTA_ModifyGold_Buyback = 2,
    DOTA_ModifyGold_PurchaseConsumable = 3,
    DOTA_ModifyGold_PurchaseItem = 4,
    DOTA_ModifyGold_AbandonedRedistribute = 5,
    DOTA_ModifyGold_SellItem = 6,
    DOTA_ModifyGold_AbilityCost = 7,
    DOTA_ModifyGold_CheatCommand = 8,
    DOTA_ModifyGold_SelectionPenalty = 9,
    DOTA_ModifyGold_GameTick = 10,
    DOTA_ModifyGold_Building = 11,
    DOTA_ModifyGold_HeroKill = 12,
    DOTA_ModifyGold_CreepKill = 13,
    DOTA_ModifyGold_NeutralKill = 14,
    DOTA_ModifyGold_RoshanKill = 15,
    DOTA_ModifyGold_CourierKill = 16,
    DOTA_ModifyGold_BountyRune = 17,
    DOTA_ModifyGold_SharedGold = 18,
    DOTA_ModifyGold_AbilityGold = 19,
    DOTA_ModifyGold_WardKill = 20,
    DOTA_ModifyGold_CourierKilledByThisPlayer = 21,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitAttackCapability = DOTAUnitAttackCapability_t;

declare enum DOTAUnitAttackCapability_t {
    DOTA_UNIT_CAP_NO_ATTACK = 0,
    DOTA_UNIT_CAP_MELEE_ATTACK = 1,
    DOTA_UNIT_CAP_RANGED_ATTACK = 2,
    DOTA_UNIT_CAP_RANGED_ATTACK_DIRECTIONAL = 4,
    DOTA_UNIT_ATTACK_CAPABILITY_BIT_COUNT = 3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type UnitMoveCapability = DOTAUnitMoveCapability_t;

declare enum DOTAUnitMoveCapability_t {
    DOTA_UNIT_CAP_MOVE_NONE = 0,
    DOTA_UNIT_CAP_MOVE_GROUND = 1,
    DOTA_UNIT_CAP_MOVE_FLY = 2,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ItemShareability = EShareAbility;

declare enum EShareAbility {
    ITEM_FULLY_SHAREABLE = 0,
    ITEM_PARTIALLY_SHAREABLE = 1,
    ITEM_NOT_SHAREABLE = 2,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type MusicStatus = DOTAMusicStatus_t;

declare enum DOTAMusicStatus_t {
    DOTA_MUSIC_STATUS_NONE = 0,
    DOTA_MUSIC_STATUS_EXPLORATION = 1,
    DOTA_MUSIC_STATUS_BATTLE = 2,
    DOTA_MUSIC_STATUS_PRE_GAME_EXPLORATION = 3,
    DOTA_MUSIC_STATUS_DEAD = 4,
    DOTA_MUSIC_STATUS_LAST = 5,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type AbilityBehavior = DOTA_ABILITY_BEHAVIOR;

declare enum DOTA_ABILITY_BEHAVIOR {
    DOTA_ABILITY_BEHAVIOR_NONE = 0,
    DOTA_ABILITY_BEHAVIOR_HIDDEN = 1,
    DOTA_ABILITY_BEHAVIOR_PASSIVE = 2,
    DOTA_ABILITY_BEHAVIOR_NO_TARGET = 4,
    DOTA_ABILITY_BEHAVIOR_UNIT_TARGET = 8,
    DOTA_ABILITY_BEHAVIOR_POINT = 16,
    DOTA_ABILITY_BEHAVIOR_AOE = 32,
    DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE = 64,
    DOTA_ABILITY_BEHAVIOR_CHANNELLED = 128,
    DOTA_ABILITY_BEHAVIOR_ITEM = 256,
    DOTA_ABILITY_BEHAVIOR_TOGGLE = 512,
    DOTA_ABILITY_BEHAVIOR_DIRECTIONAL = 1024,
    DOTA_ABILITY_BEHAVIOR_IMMEDIATE = 2048,
    DOTA_ABILITY_BEHAVIOR_AUTOCAST = 4096,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET = 8192,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT = 16384,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET = 32768,
    DOTA_ABILITY_BEHAVIOR_AURA = 65536,
    DOTA_ABILITY_BEHAVIOR_ATTACK = 131072,
    DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT = 262144,
    DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES = 524288,
    DOTA_ABILITY_BEHAVIOR_UNRESTRICTED = 1048576,
    DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE = 2097152,
    DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL = 4194304,
    DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT = 8388608,
    DOTA_ABILITY_BEHAVIOR_DONT_ALERT_TARGET = 16777216,
    DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK = 33554432,
    DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN = 67108864,
    DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING = 134217728,
    DOTA_ABILITY_BEHAVIOR_RUNE_TARGET = 268435456,
    DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL = 536870912,
    DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING = 1073741824,
    DOTA_ABILITY_BEHAVIOR_LAST_RESORT_POINT = 2147483648,
    DOTA_ABILITY_BEHAVIOR_CAN_SELF_CAST = 4294967296,
    DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES = 8589934592,
    DOTA_ABILITY_BEHAVIOR_UNLOCKED_BY_EFFECT_INDEX = 17179869184,
    DOTA_ABILITY_BEHAVIOR_SUPPRESS_ASSOCIATED_CONSUMABLE = 34359738368,
    DOTA_ABILITY_BEHAVIOR_FREE_DRAW_TARGETING = 68719476736,
    DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE = 137438953472,
    DOTA_ABILITY_BEHAVIOR_OVERSHOOT = 274877906944,
    DOTA_ABILITY_BEHAVIOR_IGNORE_MUTED = 549755813888,
    DOTA_ABILITY_BEHAVIOR_ALT_CASTABLE = 1099511627776,
    DOTA_ABILITY_BEHAVIOR_SKIP_FOR_KEYBINDS = 4398046511104,
    DOTA_ABILITY_BEHAVIOR_INNATE_UI = 8796093022208,
    DOTA_ABILITY_BEHAVIOR_UNSWAPPABLE = 17592186044416,
    DOTA_ABILITY_BEHAVIOR_DONT_PROC_OTHER_ABILITIES = 35184372088832,
    DOTA_ABILITY_BEHAVIOR_IGNORE_INVISIBLE = 70368744177664,
    DOTA_ABILITY_BEHAVIOR_AFFECTED_BY_MUTE = 140737488355328,
    DOTA_ABILITY_BEHAVIOR_IS_FAKE_ITEM = 281474976710656,
    DOTA_ABILITY_BEHAVIOR_FORCE_NO_INNATE_UI = 562949953421312,
    DOTA_ABILITY_BEHAVIOR_FORCE_KEYBIND = 1125899906842624,
    DOTA_ABILITY_BEHAVIOR_ITEM_IMBUE = 2251799813685248,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type DamageTypes = DAMAGE_TYPES;

declare enum DAMAGE_TYPES {
    DAMAGE_TYPE_NONE = 0,
    DAMAGE_TYPE_PHYSICAL = 1,
    DAMAGE_TYPE_MAGICAL = 2,
    DAMAGE_TYPE_PURE = 4,
    DAMAGE_TYPE_HP_REMOVAL = 8,
    DAMAGE_TYPE_ABILITY_DEFINED = 16,
    DAMAGE_TYPE_ALL = 7,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type AbilityTypes = ABILITY_TYPES;

declare enum ABILITY_TYPES {
    ABILITY_TYPE_BASIC = 0,
    ABILITY_TYPE_ULTIMATE = 1,
    ABILITY_TYPE_ATTRIBUTES = 2,
    ABILITY_TYPE_HIDDEN = 3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type SpellImmunityTypes = SPELL_IMMUNITY_TYPES;

declare enum SPELL_IMMUNITY_TYPES {
    SPELL_IMMUNITY_NONE = 0,
    SPELL_IMMUNITY_ALLIES_YES = 1,
    SPELL_IMMUNITY_ALLIES_NO = 2,
    SPELL_IMMUNITY_ENEMIES_YES = 3,
    SPELL_IMMUNITY_ENEMIES_NO = 4,
    SPELL_IMMUNITY_ALLIES_YES_ENEMIES_NO = 5,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type DamageFlag = DOTADamageFlag_t;

declare enum DOTADamageFlag_t {
    DOTA_DAMAGE_FLAG_NONE = 0,
    DOTA_DAMAGE_FLAG_IGNORES_MAGIC_ARMOR = 1,
    DOTA_DAMAGE_FLAG_IGNORES_PHYSICAL_ARMOR = 2,
    DOTA_DAMAGE_FLAG_BYPASSES_INVULNERABILITY = 4,
    DOTA_DAMAGE_FLAG_BYPASSES_PHYSICAL_BLOCK = 8,
    DOTA_DAMAGE_FLAG_REFLECTION = 16,
    DOTA_DAMAGE_FLAG_HPLOSS = 32,
    DOTA_DAMAGE_FLAG_NO_DIRECTOR_EVENT = 64,
    DOTA_DAMAGE_FLAG_NON_LETHAL = 128,
    DOTA_DAMAGE_FLAG_NO_DAMAGE_MULTIPLIERS = 512,
    DOTA_DAMAGE_FLAG_NO_SPELL_AMPLIFICATION = 1024,
    DOTA_DAMAGE_FLAG_DONT_DISPLAY_DAMAGE_IF_SOURCE_HIDDEN = 2048,
    DOTA_DAMAGE_FLAG_NO_SPELL_LIFESTEAL = 4096,
    DOTA_DAMAGE_FLAG_PROPERTY_FIRE = 8192,
    DOTA_DAMAGE_FLAG_IGNORES_BASE_PHYSICAL_ARMOR = 16384,
    DOTA_DAMAGE_FLAG_SECONDARY_PROJECTILE_ATTACK = 32768,
    DOTA_DAMAGE_FLAG_FORCE_SPELL_AMPLIFICATION = 65536,
    DOTA_DAMAGE_FLAG_MAGIC_AUTO_ATTACK = 131072,
    DOTA_DAMAGE_FLAG_ATTACK_MODIFIER = 262144,
    DOTA_DAMAGE_FLAG_BYPASSES_ALL_BLOCK = 524288,
    DOTA_DAMAGE_FLAG_NO_REFLECTION = 1048576,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ModifyXpReason = EDOTA_ModifyXP_Reason;

declare enum EDOTA_ModifyXP_Reason {
    DOTA_ModifyXP_Unspecified = 0,
    DOTA_ModifyXP_HeroKill = 1,
    DOTA_ModifyXP_CreepKill = 2,
    DOTA_ModifyXP_RoshanKill = 3,
    DOTA_ModifyXP_TomeOfKnowledge = 4,
    DOTA_ModifyXP_Outpost = 5,
    DOTA_ModifyXP_CatchUp = 6,
    DOTA_ModifyXP_HeroAbility = 7,
    DOTA_ModifyXP_MAX = 8,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type GameActivity = GameActivity_t;

declare enum GameActivity_t {
    ACT_DOTA_IDLE = 1500,
    ACT_DOTA_IDLE_RARE = 1501,
    ACT_DOTA_RUN = 1502,
    ACT_DOTA_ATTACK = 1503,
    ACT_DOTA_ATTACK2 = 1504,
    ACT_DOTA_ATTACK_EVENT = 1505,
    ACT_DOTA_DIE = 1506,
    ACT_DOTA_FLINCH = 1507,
    ACT_DOTA_FLAIL = 1508,
    ACT_DOTA_DISABLED = 1509,
    ACT_DOTA_CAST_ABILITY_1 = 1510,
    ACT_DOTA_CAST_ABILITY_2 = 1511,
    ACT_DOTA_CAST_ABILITY_3 = 1512,
    ACT_DOTA_CAST_ABILITY_4 = 1513,
    ACT_DOTA_CAST_ABILITY_5 = 1514,
    ACT_DOTA_CAST_ABILITY_6 = 1515,
    ACT_DOTA_OVERRIDE_ABILITY_1 = 1516,
    ACT_DOTA_OVERRIDE_ABILITY_2 = 1517,
    ACT_DOTA_OVERRIDE_ABILITY_3 = 1518,
    ACT_DOTA_OVERRIDE_ABILITY_4 = 1519,
    ACT_DOTA_CHANNEL_ABILITY_1 = 1520,
    ACT_DOTA_CHANNEL_ABILITY_2 = 1521,
    ACT_DOTA_CHANNEL_ABILITY_3 = 1522,
    ACT_DOTA_CHANNEL_ABILITY_4 = 1523,
    ACT_DOTA_CHANNEL_ABILITY_5 = 1524,
    ACT_DOTA_CHANNEL_ABILITY_6 = 1525,
    ACT_DOTA_CHANNEL_END_ABILITY_1 = 1526,
    ACT_DOTA_CHANNEL_END_ABILITY_2 = 1527,
    ACT_DOTA_CHANNEL_END_ABILITY_3 = 1528,
    ACT_DOTA_CHANNEL_END_ABILITY_4 = 1529,
    ACT_DOTA_CHANNEL_END_ABILITY_5 = 1530,
    ACT_DOTA_CHANNEL_END_ABILITY_6 = 1531,
    ACT_DOTA_CONSTANT_LAYER = 1532,
    ACT_DOTA_CAPTURE = 1533,
    ACT_DOTA_SPAWN = 1534,
    ACT_DOTA_KILLTAUNT = 1535,
    ACT_DOTA_TAUNT = 1536,
    ACT_DOTA_THIRST = 1537,
    ACT_DOTA_CAST_DRAGONBREATH = 1538,
    ACT_DOTA_ECHO_SLAM = 1539,
    ACT_DOTA_CAST_ABILITY_1_END = 1540,
    ACT_DOTA_CAST_ABILITY_2_END = 1541,
    ACT_DOTA_CAST_ABILITY_3_END = 1542,
    ACT_DOTA_CAST_ABILITY_4_END = 1543,
    ACT_MIRANA_LEAP_END = 1544,
    ACT_WAVEFORM_START = 1545,
    ACT_WAVEFORM_END = 1546,
    ACT_DOTA_CAST_ABILITY_ROT = 1547,
    ACT_DOTA_DIE_SPECIAL = 1548,
    ACT_DOTA_RATTLETRAP_BATTERYASSAULT = 1549,
    ACT_DOTA_RATTLETRAP_POWERCOGS = 1550,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_START = 1551,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_LOOP = 1552,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_END = 1553,
    ACT_STORM_SPIRIT_OVERLOAD_RUN_OVERRIDE = 1554,
    ACT_DOTA_TINKER_REARM1 = 1555,
    ACT_DOTA_TINKER_REARM2 = 1556,
    ACT_DOTA_TINKER_REARM3 = 1557,
    ACT_TINY_AVALANCHE = 1558,
    ACT_TINY_TOSS = 1559,
    ACT_TINY_GROWL = 1560,
    ACT_DOTA_WEAVERBUG_ATTACH = 1561,
    ACT_DOTA_CAST_WILD_AXES_END = 1562,
    ACT_DOTA_CAST_LIFE_BREAK_START = 1563,
    ACT_DOTA_CAST_LIFE_BREAK_END = 1564,
    ACT_DOTA_NIGHTSTALKER_TRANSITION = 1565,
    ACT_DOTA_LIFESTEALER_RAGE = 1566,
    ACT_DOTA_LIFESTEALER_OPEN_WOUNDS = 1567,
    ACT_DOTA_SAND_KING_BURROW_IN = 1568,
    ACT_DOTA_SAND_KING_BURROW_OUT = 1569,
    ACT_DOTA_EARTHSHAKER_TOTEM_ATTACK = 1570,
    ACT_DOTA_WHEEL_LAYER = 1571,
    ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_START = 1572,
    ACT_DOTA_ALCHEMIST_CONCOCTION = 1573,
    ACT_DOTA_JAKIRO_LIQUIDFIRE_START = 1574,
    ACT_DOTA_JAKIRO_LIQUIDFIRE_LOOP = 1575,
    ACT_DOTA_LIFESTEALER_INFEST = 1576,
    ACT_DOTA_LIFESTEALER_INFEST_END = 1577,
    ACT_DOTA_LASSO_LOOP = 1578,
    ACT_DOTA_ALCHEMIST_CONCOCTION_THROW = 1579,
    ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_END = 1580,
    ACT_DOTA_CAST_COLD_SNAP = 1581,
    ACT_DOTA_CAST_GHOST_WALK = 1582,
    ACT_DOTA_CAST_TORNADO = 1583,
    ACT_DOTA_CAST_EMP = 1584,
    ACT_DOTA_CAST_ALACRITY = 1585,
    ACT_DOTA_CAST_CHAOS_METEOR = 1586,
    ACT_DOTA_CAST_SUN_STRIKE = 1587,
    ACT_DOTA_CAST_FORGE_SPIRIT = 1588,
    ACT_DOTA_CAST_ICE_WALL = 1589,
    ACT_DOTA_CAST_DEAFENING_BLAST = 1590,
    ACT_DOTA_VICTORY = 1591,
    ACT_DOTA_DEFEAT = 1592,
    ACT_DOTA_SPIRIT_BREAKER_CHARGE_POSE = 1593,
    ACT_DOTA_SPIRIT_BREAKER_CHARGE_END = 1594,
    ACT_DOTA_TELEPORT = 1595,
    ACT_DOTA_TELEPORT_END = 1596,
    ACT_DOTA_CAST_REFRACTION = 1597,
    ACT_DOTA_CAST_ABILITY_7 = 1598,
    ACT_DOTA_CANCEL_SIREN_SONG = 1599,
    ACT_DOTA_CHANNEL_ABILITY_7 = 1600,
    ACT_DOTA_LOADOUT = 1601,
    ACT_DOTA_FORCESTAFF_END = 1602,
    ACT_DOTA_POOF_END = 1603,
    ACT_DOTA_SLARK_POUNCE = 1604,
    ACT_DOTA_MAGNUS_SKEWER_START = 1605,
    ACT_DOTA_MAGNUS_SKEWER_END = 1606,
    ACT_DOTA_MEDUSA_STONE_GAZE = 1607,
    ACT_DOTA_RELAX_START = 1608,
    ACT_DOTA_RELAX_LOOP = 1609,
    ACT_DOTA_RELAX_END = 1610,
    ACT_DOTA_CENTAUR_STAMPEDE = 1611,
    ACT_DOTA_BELLYACHE_START = 1612,
    ACT_DOTA_BELLYACHE_LOOP = 1613,
    ACT_DOTA_BELLYACHE_END = 1614,
    ACT_DOTA_ROQUELAIRE_LAND = 1615,
    ACT_DOTA_ROQUELAIRE_LAND_IDLE = 1616,
    ACT_DOTA_GREEVIL_CAST = 1617,
    ACT_DOTA_GREEVIL_OVERRIDE_ABILITY = 1618,
    ACT_DOTA_GREEVIL_HOOK_START = 1619,
    ACT_DOTA_GREEVIL_HOOK_END = 1620,
    ACT_DOTA_GREEVIL_BLINK_BONE = 1621,
    ACT_DOTA_IDLE_SLEEPING = 1622,
    ACT_DOTA_INTRO = 1623,
    ACT_DOTA_GESTURE_POINT = 1624,
    ACT_DOTA_GESTURE_ACCENT = 1625,
    ACT_DOTA_SLEEPING_END = 1626,
    ACT_DOTA_AMBUSH = 1627,
    ACT_DOTA_ITEM_LOOK = 1628,
    ACT_DOTA_STARTLE = 1629,
    ACT_DOTA_FRUSTRATION = 1630,
    ACT_DOTA_TELEPORT_REACT = 1631,
    ACT_DOTA_TELEPORT_END_REACT = 1632,
    ACT_DOTA_SHRUG = 1633,
    ACT_DOTA_RELAX_LOOP_END = 1634,
    ACT_DOTA_PRESENT_ITEM = 1635,
    ACT_DOTA_IDLE_IMPATIENT = 1636,
    ACT_DOTA_SHARPEN_WEAPON = 1637,
    ACT_DOTA_SHARPEN_WEAPON_OUT = 1638,
    ACT_DOTA_IDLE_SLEEPING_END = 1639,
    ACT_DOTA_BRIDGE_DESTROY = 1640,
    ACT_DOTA_TAUNT_SNIPER = 1641,
    ACT_DOTA_DEATH_BY_SNIPER = 1642,
    ACT_DOTA_LOOK_AROUND = 1643,
    ACT_DOTA_CAGED_CREEP_RAGE = 1644,
    ACT_DOTA_CAGED_CREEP_RAGE_OUT = 1645,
    ACT_DOTA_CAGED_CREEP_SMASH = 1646,
    ACT_DOTA_CAGED_CREEP_SMASH_OUT = 1647,
    ACT_DOTA_IDLE_IMPATIENT_SWORD_TAP = 1648,
    ACT_DOTA_INTRO_LOOP = 1649,
    ACT_DOTA_BRIDGE_THREAT = 1650,
    ACT_DOTA_DAGON = 1651,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL_START = 1652,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL = 1653,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL_END = 1654,
    ACT_DOTA_NIAN_PIN_START = 1655,
    ACT_DOTA_NIAN_PIN_LOOP = 1656,
    ACT_DOTA_NIAN_PIN_END = 1657,
    ACT_DOTA_LEAP_STUN = 1658,
    ACT_DOTA_LEAP_SWIPE = 1659,
    ACT_DOTA_NIAN_INTRO_LEAP = 1660,
    ACT_DOTA_AREA_DENY = 1661,
    ACT_DOTA_NIAN_PIN_TO_STUN = 1662,
    ACT_DOTA_RAZE_1 = 1663,
    ACT_DOTA_RAZE_2 = 1664,
    ACT_DOTA_RAZE_3 = 1665,
    ACT_DOTA_UNDYING_DECAY = 1666,
    ACT_DOTA_UNDYING_SOUL_RIP = 1667,
    ACT_DOTA_UNDYING_TOMBSTONE = 1668,
    ACT_DOTA_WHIRLING_AXES_RANGED = 1669,
    ACT_DOTA_SHALLOW_GRAVE = 1670,
    ACT_DOTA_COLD_FEET = 1671,
    ACT_DOTA_ICE_VORTEX = 1672,
    ACT_DOTA_CHILLING_TOUCH = 1673,
    ACT_DOTA_ENFEEBLE = 1674,
    ACT_DOTA_FATAL_BONDS = 1675,
    ACT_DOTA_MIDNIGHT_PULSE = 1676,
    ACT_DOTA_ANCESTRAL_SPIRIT = 1677,
    ACT_DOTA_THUNDER_STRIKE = 1678,
    ACT_DOTA_KINETIC_FIELD = 1679,
    ACT_DOTA_STATIC_STORM = 1680,
    ACT_DOTA_MINI_TAUNT = 1681,
    ACT_DOTA_ARCTIC_BURN_END = 1682,
    ACT_DOTA_LOADOUT_RARE = 1683,
    ACT_DOTA_SWIM = 1684,
    ACT_DOTA_FLEE = 1685,
    ACT_DOTA_TROT = 1686,
    ACT_DOTA_SHAKE = 1687,
    ACT_DOTA_SWIM_IDLE = 1688,
    ACT_DOTA_WAIT_IDLE = 1689,
    ACT_DOTA_GREET = 1690,
    ACT_DOTA_TELEPORT_COOP_START = 1691,
    ACT_DOTA_TELEPORT_COOP_WAIT = 1692,
    ACT_DOTA_TELEPORT_COOP_END = 1693,
    ACT_DOTA_TELEPORT_COOP_EXIT = 1694,
    ACT_DOTA_SHOPKEEPER_PET_INTERACT = 1695,
    ACT_DOTA_ITEM_PICKUP = 1696,
    ACT_DOTA_ITEM_DROP = 1697,
    ACT_DOTA_CAPTURE_PET = 1698,
    ACT_DOTA_PET_WARD_OBSERVER = 1699,
    ACT_DOTA_PET_WARD_SENTRY = 1700,
    ACT_DOTA_PET_LEVEL = 1701,
    ACT_DOTA_CAST_BURROW_END = 1702,
    ACT_DOTA_LIFESTEALER_ASSIMILATE = 1703,
    ACT_DOTA_LIFESTEALER_EJECT = 1704,
    ACT_DOTA_ATTACK_EVENT_BASH = 1705,
    ACT_DOTA_CAPTURE_RARE = 1706,
    ACT_DOTA_AW_MAGNETIC_FIELD = 1707,
    ACT_DOTA_CAST_GHOST_SHIP = 1708,
    ACT_DOTA_FXANIM = 1709,
    ACT_DOTA_VICTORY_START = 1710,
    ACT_DOTA_DEFEAT_START = 1711,
    ACT_DOTA_DP_SPIRIT_SIPHON = 1712,
    ACT_DOTA_TRICKS_END = 1713,
    ACT_DOTA_ES_STONE_CALLER = 1714,
    ACT_DOTA_MK_STRIKE = 1715,
    ACT_DOTA_VERSUS = 1716,
    ACT_DOTA_CAPTURE_CARD = 1717,
    ACT_DOTA_MK_SPRING_SOAR = 1718,
    ACT_DOTA_MK_SPRING_END = 1719,
    ACT_DOTA_MK_TREE_SOAR = 1720,
    ACT_DOTA_MK_TREE_END = 1721,
    ACT_DOTA_MK_FUR_ARMY = 1722,
    ACT_DOTA_MK_SPRING_CAST = 1723,
    ACT_DOTA_NECRO_GHOST_SHROUD = 1724,
    ACT_DOTA_OVERRIDE_ARCANA = 1725,
    ACT_DOTA_SLIDE = 1726,
    ACT_DOTA_SLIDE_LOOP = 1727,
    ACT_DOTA_GENERIC_CHANNEL_1 = 1728,
    ACT_DOTA_GS_SOUL_CHAIN = 1729,
    ACT_DOTA_GS_INK_CREATURE = 1730,
    ACT_DOTA_TRANSITION = 1731,
    ACT_DOTA_BLINK_DAGGER = 1732,
    ACT_DOTA_BLINK_DAGGER_END = 1733,
    ACT_DOTA_CUSTOM_TOWER_ATTACK = 1734,
    ACT_DOTA_CUSTOM_TOWER_IDLE = 1735,
    ACT_DOTA_CUSTOM_TOWER_DIE = 1736,
    ACT_DOTA_CAST_COLD_SNAP_ORB = 1737,
    ACT_DOTA_CAST_GHOST_WALK_ORB = 1738,
    ACT_DOTA_CAST_TORNADO_ORB = 1739,
    ACT_DOTA_CAST_EMP_ORB = 1740,
    ACT_DOTA_CAST_ALACRITY_ORB = 1741,
    ACT_DOTA_CAST_CHAOS_METEOR_ORB = 1742,
    ACT_DOTA_CAST_SUN_STRIKE_ORB = 1743,
    ACT_DOTA_CAST_FORGE_SPIRIT_ORB = 1744,
    ACT_DOTA_CAST_ICE_WALL_ORB = 1745,
    ACT_DOTA_CAST_DEAFENING_BLAST_ORB = 1746,
    ACT_DOTA_NOTICE = 1747,
    ACT_DOTA_CAST_ABILITY_2_ALLY = 1748,
    ACT_DOTA_SHUFFLE_L = 1749,
    ACT_DOTA_SHUFFLE_R = 1750,
    ACT_DOTA_OVERRIDE_LOADOUT = 1751,
    ACT_DOTA_TAUNT_SPECIAL = 1752,
    ACT_DOTA_TELEPORT_START = 1753,
    ACT_DOTA_GENERIC_CHANNEL_1_START = 1754,
    ACT_DOTA_CUSTOM_TOWER_IDLE_RARE = 1755,
    ACT_DOTA_CUSTOM_TOWER_TAUNT = 1756,
    ACT_DOTA_CUSTOM_TOWER_HIGH_FIVE = 1757,
    ACT_DOTA_ATTACK_SPECIAL = 1758,
    ACT_DOTA_TRANSITION_IDLE = 1759,
    ACT_DOTA_PIERCE_THE_VEIL = 1760,
    ACT_DOTA_RUN_RARE = 1761,
    ACT_DOTA_VIPER_DIVE = 1762,
    ACT_DOTA_VIPER_DIVE_END = 1763,
    ACT_DOTA_MK_STRIKE_END = 1764,
    ACT_DOTA_SHADOW_VAULT = 1765,
    ACT_DOTA_KEZ_KATANA_ULT_START = 1766,
    ACT_DOTA_KEZ_KATANA_ULT_CHAIN_A = 1767,
    ACT_DOTA_KEZ_KATANA_ULT_CHAIN_B = 1768,
    ACT_DOTA_KEZ_KATANA_ULT_END = 1769,
    ACT_DOTA_KEZ_KATANA_IMPALE = 1770,
    ACT_DOTA_KEZ_KATANA_IMPALE_FAST = 1771,
    ACT_DOTA_UNICYCLE = 1772,
    ACT_DOTA_UNICYCLE_END = 1773,
    ACT_DOTA_LARGO_ULT_STRUM_SUCCESS = 1774,
    ACT_DOTA_LARGO_ULT_STRUM_FAIL = 1775,
    ACT_DOTA_MVP_SCREEN = 1776,
    ACT_DOTA_LARGO_ULT_TOGGLE_ON = 1777,
    ACT_DOTA_LARGO_ULT_TOGGLE_OFF = 1778,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type MinimapEventType = DOTAMinimapEvent_t;

declare enum DOTAMinimapEvent_t {
    DOTA_MINIMAP_EVENT_ANCIENT_UNDER_ATTACK = 2,
    DOTA_MINIMAP_EVENT_BASE_UNDER_ATTACK = 4,
    DOTA_MINIMAP_EVENT_BASE_GLYPHED = 8,
    DOTA_MINIMAP_EVENT_TEAMMATE_UNDER_ATTACK = 16,
    DOTA_MINIMAP_EVENT_TEAMMATE_TELEPORTING = 32,
    DOTA_MINIMAP_EVENT_TEAMMATE_DIED = 64,
    DOTA_MINIMAP_EVENT_TUTORIAL_TASK_ACTIVE = 128,
    DOTA_MINIMAP_EVENT_TUTORIAL_TASK_FINISHED = 256,
    DOTA_MINIMAP_EVENT_HINT_LOCATION = 512,
    DOTA_MINIMAP_EVENT_ENEMY_TELEPORTING = 1024,
    DOTA_MINIMAP_EVENT_CANCEL_TELEPORTING = 2048,
    DOTA_MINIMAP_EVENT_RADAR = 4096,
    DOTA_MINIMAP_EVENT_RADAR_TARGET = 8192,
    DOTA_MINIMAP_EVENT_MOVE_TO_TARGET = 16384,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type LoadoutType = DOTASlotType_t;

declare enum DOTASlotType_t {
    DOTA_LOADOUT_TYPE_INVALID = -1,
    DOTA_LOADOUT_TYPE_WEAPON = 0,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON = 1,
    DOTA_LOADOUT_TYPE_WEAPON2 = 2,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2 = 3,
    DOTA_LOADOUT_TYPE_HEAD = 4,
    DOTA_LOADOUT_TYPE_SHOULDER = 5,
    DOTA_LOADOUT_TYPE_ARMS = 6,
    DOTA_LOADOUT_TYPE_ARMOR = 7,
    DOTA_LOADOUT_TYPE_BELT = 8,
    DOTA_LOADOUT_TYPE_NECK = 9,
    DOTA_LOADOUT_TYPE_BACK = 10,
    DOTA_LOADOUT_TYPE_GLOVES = 11,
    DOTA_LOADOUT_TYPE_LEGS = 12,
    DOTA_LOADOUT_TYPE_TAIL = 13,
    DOTA_LOADOUT_TYPE_MISC = 14,
    DOTA_LOADOUT_TYPE_COSTUME = 15,
    DOTA_LOADOUT_TYPE_HERO_BASE = 16,
    DOTA_LOADOUT_TYPE_BODY_HEAD = 17,
    DOTA_LOADOUT_TYPE_MOUNT = 18,
    DOTA_LOADOUT_TYPE_SUMMON = 19,
    DOTA_LOADOUT_TYPE_SHAPESHIFT = 20,
    DOTA_LOADOUT_TYPE_TAUNT = 21,
    DOTA_LOADOUT_TYPE_HERO_EFFIGY = 22,
    DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS = 23,
    DOTA_LOADOUT_TYPE_ABILITY_ATTACK = 24,
    DOTA_LOADOUT_TYPE_ABILITY1 = 25,
    DOTA_LOADOUT_TYPE_ABILITY2 = 26,
    DOTA_LOADOUT_TYPE_ABILITY3 = 27,
    DOTA_LOADOUT_TYPE_ABILITY4 = 28,
    DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE = 29,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_1 = 30,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_2 = 31,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_3 = 32,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_4 = 33,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_5 = 34,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_6 = 35,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_7 = 36,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_8 = 37,
    DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_9 = 38,
    DOTA_LOADOUT_TYPE_VOICE = 39,
    DOTA_LOADOUT_TYPE_WEAPON_PERSONA_1 = 40,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON_PERSONA_1 = 41,
    DOTA_LOADOUT_TYPE_WEAPON2_PERSONA_1 = 42,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2_PERSONA_1 = 43,
    DOTA_LOADOUT_TYPE_HEAD_PERSONA_1 = 44,
    DOTA_LOADOUT_TYPE_SHOULDER_PERSONA_1 = 45,
    DOTA_LOADOUT_TYPE_ARMS_PERSONA_1 = 46,
    DOTA_LOADOUT_TYPE_ARMOR_PERSONA_1 = 47,
    DOTA_LOADOUT_TYPE_BELT_PERSONA_1 = 48,
    DOTA_LOADOUT_TYPE_NECK_PERSONA_1 = 49,
    DOTA_LOADOUT_TYPE_BACK_PERSONA_1 = 50,
    DOTA_LOADOUT_TYPE_LEGS_PERSONA_1 = 51,
    DOTA_LOADOUT_TYPE_GLOVES_PERSONA_1 = 52,
    DOTA_LOADOUT_TYPE_TAIL_PERSONA_1 = 53,
    DOTA_LOADOUT_TYPE_MISC_PERSONA_1 = 54,
    DOTA_LOADOUT_TYPE_BODY_HEAD_PERSONA_1 = 55,
    DOTA_LOADOUT_TYPE_MOUNT_PERSONA_1 = 56,
    DOTA_LOADOUT_TYPE_SUMMON_PERSONA_1 = 57,
    DOTA_LOADOUT_TYPE_SHAPESHIFT_PERSONA_1 = 58,
    DOTA_LOADOUT_TYPE_TAUNT_PERSONA_1 = 59,
    DOTA_LOADOUT_TYPE_HERO_EFFIGY_PERSONA_1 = 60,
    DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS_PERSONA_1 = 61,
    DOTA_LOADOUT_TYPE_ABILITY_ATTACK_PERSONA_1 = 62,
    DOTA_LOADOUT_TYPE_ABILITY1_PERSONA_1 = 63,
    DOTA_LOADOUT_TYPE_ABILITY2_PERSONA_1 = 64,
    DOTA_LOADOUT_TYPE_ABILITY3_PERSONA_1 = 65,
    DOTA_LOADOUT_TYPE_ABILITY4_PERSONA_1 = 66,
    DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE_PERSONA_1 = 67,
    DOTA_LOADOUT_TYPE_VOICE_PERSONA_1 = 68,
    DOTA_LOADOUT_PERSONA_1_START = 40,
    DOTA_LOADOUT_PERSONA_1_END = 68,
    DOTA_LOADOUT_TYPE_PERSONA_SELECTOR = 69,
    DOTA_LOADOUT_TYPE_COURIER = 70,
    DOTA_LOADOUT_TYPE_ANNOUNCER = 71,
    DOTA_LOADOUT_TYPE_MEGA_KILLS = 72,
    DOTA_LOADOUT_TYPE_MUSIC = 73,
    DOTA_LOADOUT_TYPE_WARD = 74,
    DOTA_LOADOUT_TYPE_HUD_SKIN = 75,
    DOTA_LOADOUT_TYPE_LOADING_SCREEN = 76,
    DOTA_LOADOUT_TYPE_WEATHER = 77,
    DOTA_LOADOUT_TYPE_HEROIC_STATUE = 78,
    DOTA_LOADOUT_TYPE_MULTIKILL_BANNER = 79,
    DOTA_LOADOUT_TYPE_CURSOR_PACK = 80,
    DOTA_LOADOUT_TYPE_TELEPORT_EFFECT = 81,
    DOTA_LOADOUT_TYPE_BLINK_EFFECT = 82,
    DOTA_LOADOUT_TYPE_EMBLEM = 83,
    DOTA_LOADOUT_TYPE_TERRAIN = 84,
    DOTA_LOADOUT_TYPE_RADIANT_CREEPS = 85,
    DOTA_LOADOUT_TYPE_DIRE_CREEPS = 86,
    DOTA_LOADOUT_TYPE_RADIANT_TOWER = 87,
    DOTA_LOADOUT_TYPE_DIRE_TOWER = 88,
    DOTA_LOADOUT_TYPE_VERSUS_SCREEN = 89,
    DOTA_LOADOUT_TYPE_STREAK_EFFECT = 90,
    DOTA_LOADOUT_TYPE_KILL_EFFECT = 91,
    DOTA_LOADOUT_TYPE_DEATH_EFFECT = 92,
    DOTA_LOADOUT_TYPE_HEAD_EFFECT = 93,
    DOTA_LOADOUT_TYPE_MAP_EFFECT = 94,
    DOTA_LOADOUT_TYPE_COURIER_EFFECT = 95,
    DOTA_LOADOUT_TYPE_RADIANT_SIEGE_CREEPS = 96,
    DOTA_LOADOUT_TYPE_DIRE_SIEGE_CREEPS = 97,
    DOTA_LOADOUT_TYPE_ROSHAN = 98,
    DOTA_LOADOUT_TYPE_TORMENTOR = 99,
    DOTA_LOADOUT_TYPE_ANCIENT = 100,
    DOTA_LOADOUT_TYPE_PET_EFFIGY = 101,
    DOTA_PLAYER_LOADOUT_START = 70,
    DOTA_PLAYER_LOADOUT_END = 101,
    DOTA_LOADOUT_TYPE_NONE = 102,
    DOTA_LOADOUT_TYPE_COUNT = 103,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ModifierFunction = modifierfunction;

declare enum modifierfunction {
    /**
     * 定值额外攻击力/目标额外攻击力（例：支配死灵/盛宴）
     */ MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE = 0,
    /**
     * 目标触发额外攻击力（例：摔跤行家）
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_TARGET = 1,
    /**
     * Lua不可用：触发额外攻击力（例：射手天赋）
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC = 2,
    /**
     * 后致命一击伤害（例：影刃）
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT = 3,
    /**
     * 定值基础攻击力（例：长大）
     */
    MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE = 4,
    /**
     * 物理攻击特效（例：怒意狂击）
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL = 5,
    /**
     * Lua不可用：物理魔法转化攻击特效（例：超自然）
     */
    MODIFIER_PROPERTY_PROCATTACK_CONVERT_PHYSICAL_TO_MAGICAL = 6,
    /**
     * 魔法攻击特效（例：金箍棒）
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL = 7,
    /**
     * 纯粹攻击特效（例：魔晶血怒）
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE = 8,
    /**
     * Lua不可用：目标魔法攻击特效（例：丝质重器）
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL_TARGET = 9,
    /**
     * 魔法反馈攻击特效（例：法力损毁）
     */
    MODIFIER_PROPERTY_PROCATTACK_FEEDBACK = 10,
    /**
     * 总攻击设定（例：虚张声势）
     */
    MODIFIER_PROPERTY_OVERRIDE_ATTACK_DAMAGE = 11,
    /**
     * 攻击前监听记录攻击行为（例：射手天赋）
     */
    MODIFIER_PROPERTY_PRE_ATTACK = 12,
    /**
     * 隐身透明度（例：暗影步）
     */
    MODIFIER_PROPERTY_INVISIBILITY_LEVEL = 13,
    /**
     * 攻击不打破隐身（例：暗影之舞）
     */
    MODIFIER_PROPERTY_INVISIBILITY_ATTACK_BEHAVIOR_EXCEPTION = 14,
    /**
     * 永久隐身（例：刀光谍影）
     */
    MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY = 15,
    /**
     * 定值额外移速（例：血肉傀儡）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT = 16,
    /**
     * 基础移速覆盖（例：妖术）
     */
    MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE = 17,
    /**
     * 标准移速下限设定（未知）
     */
    MODIFIER_PROPERTY_MOVESPEED_MIN_OVERRIDE = 18,
    /**
     * 标准移速上限设定（例：举步生风）
     */
    MODIFIER_PROPERTY_MOVESPEED_MAX_OVERRIDE = 19,
    /**
     * 百分比额外移速（例：黄泉颤抖）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE = 20,
    /**
     * 特殊百分比额外移速（例：夜叉）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE = 21,
    /**
     * 特殊定值额外移速（例：速度之靴）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE = 22,
    /**
     * 特殊定值额外移速2（未知）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2 = 23,
    /**
     * 唯一特殊定值额外移速（未知）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE = 24,
    /**
     * 唯一特殊定值额外移速2（例：风灵之纹）
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE_2 = 25,
    /**
     * 移速设定（例：时间结界）
     */
    MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE = 26,
    /**
     * 绝对移速下限设定（例：奔腾）
     */
    MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN = 27,
    /**
     * 绝对移速上限设定（例：重如铁锚）
     */
    MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MAX = 28,
    /**
     * 突破标准移速上限（例：焦渴）
     */
    MODIFIER_PROPERTY_IGNORE_MOVESPEED_LIMIT = 29,
    /**
     * 绝对移速上限（例：蜥蜴绝吻）
     */
    MODIFIER_PROPERTY_MOVESPEED_LIMIT = 30,
    /**
     * 攻击速度设定（未知）
     */
    MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE = 31,
    /**
     * 固定攻击间隔（例：怒拳破）
     */
    MODIFIER_PROPERTY_FIXED_ATTACK_RATE = 32,
    /**
     * 定值攻击速度（例：超强力量）
     */
    MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT = 33,
    /**
     * 突破攻速限制（例：战斗专注）
     */
    MODIFIER_PROPERTY_IGNORE_ATTACKSPEED_LIMIT = 34,
    /**
     * 定值冷却时间降低（未知）
     */
    MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT = 35,
    /**
     * 定值魔法消耗降低（未知）
     */
    MODIFIER_PROPERTY_MANACOST_REDUCTION_CONSTANT = 36,
    /**
     * Lua不可用：定值生命消耗降低（例：德尊血式）
     */
    MODIFIER_PROPERTY_HEALTHCOST_REDUCTION_CONSTANT = 37,
    /**
     * 基础攻击间隔设定（例：化学狂暴）
     */
    MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT = 38,
    /**
     * Lua不可用：定值基础攻击间隔调整（例：神杖虚妄之诺）
     */
    MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT_ADJUST = 39,
    /**
     * Lua不可用：百分比基础攻击间隔（例：中立附魔粗暴）
     */
    MODIFIER_PROPERTY_BASE_ATTACK_TIME_PERCENTAGE = 40,
    /**
     * 基础攻击前摇设定（例：严寒烧灼）
     */
    MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT = 41,
    /**
     * Lua不可用：额外攻击百分比调整（例：灵幻兵械）
     */
    MODIFIER_PROPERTY_BONUSDAMAGEOUTGOING_PERCENTAGE = 42,
    /**
     * 百分比总攻击力（例：虚弱）
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE = 43,
    /**
     * 幻象攻击伤害调整（例：幻象默认）
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION = 44,
    /**
     * Lua不可用：幻象特殊攻击伤害调整（例：幻象对建筑肉山）
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION_AMPLIFY = 45,
    /**
     * 施加方通用伤害调整（例：决斗达人）
     */
    MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE = 46,
    /**
     * 技能增强（例：血怒）
     */
    MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE = 47,
    /**
     * 特殊技能增强（例：慧光）
     */
    MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE = 48,
    /**
     * Lua不可用：目标技能增强（未知）
     */
    MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_TARGET = 49,
    /**
     * 施加方治疗调整（例：圣洁吊坠）
     */
    MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE = 50,
    /**
     * 承受方治疗调整（例：薄葬）
     */
    MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_TARGET = 51,
    /**
     * 生命恢复调整（例：淬毒武器）
     */
    MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE = 52,
    /**
     * 攻击吸血调整（例：散华）
     */
    MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE = 53,
    /**
     * 技能吸血调整（例：霜冷光环）
     */
    MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE = 54,
    /**
     * 特殊技能吸血调整（例：慧光）
     */
    MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE_UNIQUE = 55,
    /**
     * 魔法恢复调整（例：幽魂护罩）
     */
    MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE = 56,
    /**
     * 特殊魔法恢复调整（例：慧光）
     */
    MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE_UNIQUE = 57,
    /**
     * Lua不可用：魔法消耗增强（未知）
     */
    MODIFIER_PROPERTY_MANA_DRAIN_AMPLIFY_PERCENTAGE = 58,
    /**
     * 魔法获取调整（例：幽魂护罩）
     */
    MODIFIER_PROPERTY_MP_RESTORE_AMPLIFY_PERCENTAGE = 59,
    /**
     * 百分比基础额外攻击力（例：复仇光环）
     */
    MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE = 60,
    /**
     * 特殊百分比基础额外攻击力（未知）
     */
    MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE = 61,
    /**
     * 承受方通用伤害调整（例：激怒）
     */
    MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE = 62,
    /**
     * 承受方特殊物理伤害调整（例：石化凝视）
     */
    MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE = 63,
    /**
     * 物理伤害护盾（例：共鸣脉冲）
     */
    MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_CONSTANT = 64,
    /**
     * 魔法伤害护盾（例：烈火罩）
     */
    MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT = 65,
    /**
     * 闪避（例：魅影无形）
     */
    MODIFIER_PROPERTY_EVASION_CONSTANT = 66,
    /**
     * 负值闪避（未知）
     */
    MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT = 67,
    /**
     * 特殊状态抗性（例：散夜对剑）
     */
    MODIFIER_PROPERTY_STATUS_RESISTANCE = 68,
    /**
     * 状态抗性（例：威吓）
     */
    MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING = 69,
    /**
     * 负面状态增强（例：技能窃取）
     */
    MODIFIER_PROPERTY_STATUS_RESISTANCE_CASTER = 70,
    /**
     * 首端伤害无效化（例：回光返照）
     */
    MODIFIER_PROPERTY_AVOID_DAMAGE = 71,
    /**
     * 技能吸收（未知）
     */
    MODIFIER_PROPERTY_AVOID_SPELL = 72,
    /**
     * 致盲（例：旋风飞斧）
     */
    MODIFIER_PROPERTY_MISS_PERCENTAGE = 73,
    /**
     * 百分比基础护甲（例：自然秩序）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BASE_PERCENTAGE = 74,
    /**
     * Lua不可用：百分比总护甲调整（未知）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_TOTAL_PERCENTAGE = 75,
    /**
     * 定值额外护甲（例：战吼）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS = 76,
    /**
     * 特殊定值额外护甲（例：天鹰之戒）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE = 77,
    /**
     * 特殊主动定值额外护甲（例：玄冥盾牌）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE = 78,
    /**
     * Lua不可用：后结算定值护甲（例：灵魂链接）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_POST = 79,
    /**
     * Lua不可用：最低护甲设定（例：刚强巨盾）
     */
    MODIFIER_PROPERTY_MIN_PHYSICAL_ARMOR = 80,
    /**
     * 忽略物理护甲（例：一剑穿心）
     */
    MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR = 81,
    /**
     * Lua不可用：基础魔法抗性降低（例：自然秩序）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BASE_REDUCTION = 82,
    /**
     * 线性魔法抗性（未知）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION = 83,
    /**
     * 额外魔法抗性（例：法术反制）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS = 84,
    /**
     * Lua不可用：幻象魔法抗性（例：暗绘）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_ILLUSIONS = 85,
    /**
     * Lua不可用：特殊魔法抗性（未知）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_UNIQUE = 86,
    /**
     * 虚无魔法抗性（例：衰老）
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE = 87,
    /**
     * 基础魔法恢复无效化（未知）
     */
    MODIFIER_PROPERTY_BASE_MANA_REGEN = 88,
    /**
     * 定值魔法恢复（例：奥术光环）
     */
    MODIFIER_PROPERTY_MANA_REGEN_CONSTANT = 89,
    /**
     * 特殊定值魔法恢复（例：天鹰之戒）
     */
    MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE = 90,
    /**
     * 百分比最大魔法恢复（例：泉水回春）
     */
    MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE = 91,
    /**
     * 定值生命恢复（例：活性护甲）
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT = 92,
    /**
     * 百分比最大生命恢复（例：泉水回春）
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE = 93,
    /**
     * 特殊百分比生命恢复（例：恐鳌之心）
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE_UNIQUE = 94,
    /**
     * 定值最大生命值（例：活力之球）
     */
    MODIFIER_PROPERTY_HEALTH_BONUS = 95,
    /**
     * 定值最大魔法值（例：能量之球）
     */
    MODIFIER_PROPERTY_MANA_BONUS = 96,
    /**
     * 特殊定值额外力量（例：腐朽）
     */
    MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS = 97,
    /**
     * 特殊定值最大生命值（例：感染）
     */
    MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS = 98,
    /**
     * 特殊定值最大魔法值（例：灵魂之戒）
     */
    MODIFIER_PROPERTY_EXTRA_MANA_BONUS = 99,
    /**
     * Lua不可用：百分比额外最大魔法值（未知）
     */
    MODIFIER_PROPERTY_EXTRA_MANA_BONUS_PERCENTAGE = 100,
    /**
     * 百分比最大生命值（例：磐石光环）
     */
    MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE = 101,
    /**
     * 百分比最大魔法值（例：空灵挂件）
     */
    MODIFIER_PROPERTY_EXTRA_MANA_PERCENTAGE = 102,
    /**
     * 定值额外力量（例：食人魔之斧）
     */
    MODIFIER_PROPERTY_STATS_STRENGTH_BONUS = 103,
    /**
     * 定值额外敏捷（例：欢欣之刃）
     */
    MODIFIER_PROPERTY_STATS_AGILITY_BONUS = 104,
    /**
     * 定值额外智力（例：魔力法杖）
     */
    MODIFIER_PROPERTY_STATS_INTELLECT_BONUS = 105,
    /**
     * Lua不可用：百分比总力量（例：血肉傀儡）
     */
    MODIFIER_PROPERTY_STATS_STRENGTH_BONUS_PERCENTAGE = 106,
    /**
     * Lua不可用：百分比总敏捷（例：射手天赋）
     */
    MODIFIER_PROPERTY_STATS_AGILITY_BONUS_PERCENTAGE = 107,
    /**
     * Lua不可用：百分比总智力（例：通灵头带）
     */
    MODIFIER_PROPERTY_STATS_INTELLECT_BONUS_PERCENTAGE = 108,
    /**
     * Method Name: `GetModifierIntellectNone`
     */
    MODIFIER_PROPERTY_STATS_INTELLECT_NONE = 109,
    /**
     * 特殊定值施法距离（例：以太透镜）
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS = 110,
    /**
     * Lua不可用：百分比施法距离（例：折跃耀光）
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS_PERCENTAGE = 111,
    /**
     * 目标额外施法距离（未知）
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS_TARGET = 112,
    /**
     * 定值施法距离（例：奥术至尊）
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING = 113,
    /**
     * 固有攻击距离设定（例：变形）
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BASE_OVERRIDE = 114,
    /**
     * 定值攻击距离（例：瞄准）
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BONUS = 115,
    /**
     * 特殊定值攻击距离（例：魔龙枪）
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE = 116,
    /**
     * 百分比攻击距离（例：折跃耀光）
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_PERCENTAGE = 117,
    /**
     * 绝对攻击距离设定（例：变身）
     */
    MODIFIER_PROPERTY_MAX_ATTACK_RANGE = 118,
    /**
     * 定值弹道速度（例：严寒烧灼）
     */
    MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS = 119,
    /**
     * Lua不可用：百分比弹道速度（例：银闪护符）
     */
    MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS_PERCENTAGE = 120,
    /**
     * 弹道特效替换（例：魔化）
     */
    MODIFIER_PROPERTY_PROJECTILE_NAME = 121,
    /**
     * 重生（例：绝冥再生）
     */
    MODIFIER_PROPERTY_REINCARNATION = 122,
    /**
     * 关闭重生特效（未知）
     */
    MODIFIER_PROPERTY_REINCARNATION_SUPPRESS_FX = 123,
    /**
     * 特殊定值复活时间（例：吸血灵魂）
     */
    MODIFIER_PROPERTY_RESPAWNTIME = 124,
    /**
     * 百分比复活时间降低（例：吸血灵魂）
     */
    MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE = 125,
    /**
     * 定值复活时间（未知）
     */
    MODIFIER_PROPERTY_RESPAWNTIME_STACKING = 126,
    /**
     * 百分比冷却缩减（例：玲珑心）
     */
    MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE = 127,
    /**
     * Lua不可用：冷却速度调整（例：时间膨胀）
     */
    MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_ONGOING = 128,
    /**
     * 施法动作降低（例：逆转时空）
     */
    MODIFIER_PROPERTY_CASTTIME_PERCENTAGE = 129,
    /**
     * Lua不可用：百分比攻击动作（例：海象神拳！）
     */
    MODIFIER_PROPERTY_ATTACK_ANIM_TIME_PERCENTAGE = 130,
    /**
     * 特殊百分比魔法消耗降低（例：散慧对剑）
     */
    MODIFIER_PROPERTY_MANACOST_PERCENTAGE = 131,
    /**
     * 百分比魔法消耗降低（例：奥术符）
     */
    MODIFIER_PROPERTY_MANACOST_PERCENTAGE_STACKING = 132,
    /**
     * 特殊百分比生命消耗降低（未知）
     */
    MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE = 133,
    /**
     * 百分比生命消耗降低（未知）
     */
    MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE_STACKING = 134,
    /**
     * 定值死亡损失金钱（未知）
     */
    MODIFIER_PROPERTY_DEATHGOLDCOST = 135,
    /**
     * 百分比死亡损失金钱（例：海盗帽）
     */
    MODIFIER_PROPERTY_PERCENTAGE_DEATHGOLDCOST = 136,
    /**
     * 经验倍率调整（例：从众心理）
     */
    MODIFIER_PROPERTY_EXP_RATE_BOOST = 137,
    /**
     * 金钱倍率调整（未知）
     */
    MODIFIER_PROPERTY_GOLD_RATE_BOOST = 138,
    /**
     * Method Name: `GetModifierPercentageKillAssistGoldBoost`
     */
    MODIFIER_PROPERTY_KILL_ASSIST_GOLD_BOOST = 139,
    /**
     * Lua不可用：百分比经验金钱转化（未知）
     */
    MODIFIER_PROPERTY_CONVERT_EXP_TO_GOLD_PCT = 140,
    /**
     * 致命一击（例：混沌一击）
     */
    MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE = 141,
    /**
     * 目标致命一击（例：翔影之钗）
     */
    MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE = 142,
    /**
     * 魔法伤害格挡（例：凝魂之露）
     */
    MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK = 143,
    /**
     * 物理伤害格挡（例：海妖外壳）
     */
    MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK = 144,
    /**
     * 特殊物理伤害格挡（未知）
     */
    MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL = 145,
    /**
     * Method Name: `GetModifierPhysical_ConstantBlockBonus`
     */
    MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_BONUS = 146,
    /**
     * Lua不可用：近战物理伤害格挡概率覆盖（例：刚毅）
     */
    MODIFIER_PROPERTY_INNATE_DAMAGE_BLOCK_PCT_OVERRIDE = 147,
    /**
     * 前端伤害格挡（例：魔法盾）
     */
    MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR = 148,
    /**
     * 末端伤害格挡（例：肉盾）
     */
    MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK = 149,
    /**
     * 完整动画覆盖（例：太多了）
     */
    MODIFIER_PROPERTY_OVERRIDE_ANIMATION = 150,
    /**
     * 动画速率调整（例：太多了）
     */
    MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE = 151,
    /**
     * 技能抵挡（例：林肯法球）
     */
    MODIFIER_PROPERTY_ABSORB_SPELL = 152,
    /**
     * 技能反弹（例：清莲宝珠）
     */
    MODIFIER_PROPERTY_REFLECT_SPELL = 153,
    /**
     * 禁止自动攻击（例：相位转移）
     */
    MODIFIER_PROPERTY_DISABLE_AUTOATTACK = 154,
    /**
     * 定值白天视野（例：辰星破晓）
     */
    MODIFIER_PROPERTY_BONUS_DAY_VISION = 155,
    /**
     * 百分比白天视野（例：邪道私语）
     */
    MODIFIER_PROPERTY_BONUS_DAY_VISION_PERCENTAGE = 156,
    /**
     * 定值夜晚视野（例：月之祝福）
     */
    MODIFIER_PROPERTY_BONUS_NIGHT_VISION = 157,
    /**
     * 特殊定值夜晚视野（例：银月之晶）
     */
    MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE = 158,
    /**
     * 百分比日夜视野（例：老版荒芜）
     */
    MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE = 159,
    /**
     * 绝对白天视野上限设定（例：丛林之舞）
     */
    MODIFIER_PROPERTY_FIXED_DAY_VISION = 160,
    /**
     * 绝对夜晚视野上限设定（例：丛林之舞）
     */
    MODIFIER_PROPERTY_FIXED_NIGHT_VISION = 161,
    /**
     * 最低生命值设定（例：薄葬）
     */
    MODIFIER_PROPERTY_MIN_HEALTH = 162,
    /**
     * 最低魔法值设定（例：特别储备）
     */
    MODIFIER_PROPERTY_MIN_MANA = 163,
    /**
     * 物理伤害无效化（例：守护天使）
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL = 164,
    /**
     * 魔法伤害无效化（例：命运敕令）
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL = 165,
    /**
     * 纯粹伤害无效化（例：防御符文）
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE = 166,
    /**
     * 幻象标识（例：幻象默认）
     */
    MODIFIER_PROPERTY_IS_ILLUSION = 167,
    /**
     * 幻象标签（例：幻象默认）
     */
    MODIFIER_PROPERTY_ILLUSION_LABEL = 168,
    /**
     * Lua不可用：强幻象标签（例：复仇光环）
     */
    MODIFIER_PROPERTY_STRONG_ILLUSION = 169,
    /**
     * Lua不可用：可施法幻象标签（例：复仇光环）
     */
    MODIFIER_PROPERTY_SUPER_ILLUSION = 170,
    /**
     * 终极技能可施法幻象标签（例：复仇光环）
     */
    MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ULTIMATE = 171,
    /**
     * Lua不可用：死亡可获得经验（例：复仇光环）
     */
    MODIFIER_PROPERTY_XP_DURING_DEATH = 172,
    /**
     * 百分比转身速率（例：粘性燃油）
     */
    MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE = 173,
    /**
     * 转身速率覆盖（例：相位鞋）
     */
    MODIFIER_PROPERTY_TURN_RATE_OVERRIDE = 174,
    /**
     * 生命冻结（例：冰晶爆轰）
     */
    MODIFIER_PROPERTY_DISABLE_HEALING = 175,
    /**
     * Lua不可用：魔法获取无效化（例：神杖闪烁）
     */
    MODIFIER_PROPERTY_DISABLE_MANA_GAIN = 176,
    /**
     * 无视攻击距离（例：飓风长戟）
     */
    MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK = 177,
    /**
     * Lua不可用：可攻击虚无单位（例：超自然）
     */
    MODIFIER_PROPERTY_ALWAYS_ETHEREAL_ATTACK = 178,
    /**
     * 无视攻击免疫（例：超自然）
     */
    MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL = 179,
    /**
     * 即时刷新统计情况（例：奥术符）
     */
    MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH = 180,
    /**
     * 百分比小兵击杀金钱（未知）
     */
    MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER = 181,
    /**
     * 百分比其他单位击杀金钱（未知）
     */
    MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER = 182,
    /**
     * Lua不可用：禁止单位升级（未知）
     */
    MODIFIER_PROPERTY_UNIT_DISALLOW_UPGRADING = 183,
    /**
     * 持续躲避（例：老版扫射）
     */
    MODIFIER_PROPERTY_DODGE_PROJECTILE = 184,
    /**
     * Lua不可用：仅触发攻击动作特效（未知）
     */
    MODIFIER_PROPERTY_TRIGGER_COSMETIC_AND_END_ATTACK = 185,
    /**
     * 百分比属性攻击力（未知）
     */
    MODIFIER_PROPERTY_PRIMARY_STAT_DAMAGE_MULTIPLIER = 186,
    /**
     * Lua不可用：致死打击（未知）
     */
    MODIFIER_PROPERTY_PREATTACK_DEADLY_BLOW = 187,
    /**
     * Lua不可用：固守原位仍自动攻击（未知）
     */
    MODIFIER_PROPERTY_ALWAYS_AUTOATTACK_WHILE_HOLD_POSITION = 188,
    /**
     * Lua不可用：百分比物理抗性穿透（例：地狱之裂）
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 189,
    /**
     * Lua不可用：百分比魔法抗性穿透（未知）
     */
    MODIFIER_PROPERTY_MAGICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 190,
    /**
     * Lua不可用：致命一击倍率增加（未知）
     */
    MODIFIER_PROPERTY_CRITICAL_STRIKE_BONUS = 191,
    /**
     * Lua不可用：物理纯粹转化攻击特效（未知）
     */
    MODIFIER_PROPERTY_CONVERT_ATTACK_PHYSICAL_TO_PURE = 192,
    /**
     * Lua不可用：增益时间增强（例：安可）
     */
    MODIFIER_PROPERTY_BUFF_AMPLIFICATION = 193,
    /**
     * 选定施法目标时（例：老版灵匣）
     */
    MODIFIER_EVENT_ON_SPELL_TARGET_READY = 194,
    /**
     * 记录攻击时（例：神枪在手）
     */
    MODIFIER_EVENT_ON_ATTACK_RECORD = 195,
    /**
     * 开始攻击抬手时（例：不可侵犯）
     */
    MODIFIER_EVENT_ON_ATTACK_START = 196,
    /**
     * 攻击发出时（例：暗影之境）
     */
    MODIFIER_EVENT_ON_ATTACK = 197,
    /**
     * 攻击命中时（例：腐蚀兵械）
     */
    MODIFIER_EVENT_ON_ATTACK_LANDED = 198,
    /**
     * 攻击失败时（例：液态火）
     */
    MODIFIER_EVENT_ON_ATTACK_FAIL = 199,
    /**
     * 攻击友方时（未知）
     */
    MODIFIER_EVENT_ON_ATTACK_ALLIED = 200,
    /**
     * 弹道被躲避时（例：顽皮克敌）
     */
    MODIFIER_EVENT_ON_PROJECTILE_DODGE = 201,
    /**
     * 下达指令时（例：相位转移）
     */
    MODIFIER_EVENT_ON_ORDER = 202,
    /**
     * Lua不可用：收到指令时（未知）
     */
    MODIFIER_EVENT_ON_ORDER_RECEIVED = 203,
    /**
     * 单位移动时（例：隐匿）
     */
    MODIFIER_EVENT_ON_UNIT_MOVED = 204,
    /**
     * 开始施法时（未知）
     */
    MODIFIER_EVENT_ON_ABILITY_START = 205,
    /**
     * 施法完成时（例：余震）
     */
    MODIFIER_EVENT_ON_ABILITY_EXECUTED = 206,
    /**
     * 完全施放时（例：奥术积累）
     */
    MODIFIER_EVENT_ON_ABILITY_FULLY_CAST = 207,
    /**
     * 打破隐身时（例：影刃）
     */
    MODIFIER_EVENT_ON_BREAK_INVISIBILITY = 208,
    /**
     * 持续施法结束时（例：遗言）
     */
    MODIFIER_EVENT_ON_ABILITY_END_CHANNEL = 209,
    /**
     * Lua不可用：升级时（未知）
     */
    MODIFIER_EVENT_ON_PROCESS_UPGRADE = 210,
    /**
     * Lua不可用：刷新时（未知）
     */
    MODIFIER_EVENT_ON_REFRESH = 211,
    /**
     * 受到伤害时（例：腐蚀皮肤）
     */
    MODIFIER_EVENT_ON_TAKEDAMAGE = 212,
    /**
     * 阻止死亡时（例：禽戏）
     */
    MODIFIER_EVENT_ON_DEATH_PREVENTED = 213,
    /**
     * 状态改变时（例：幽魂护罩）
     */
    MODIFIER_EVENT_ON_STATE_CHANGED = 214,
    /**
     * Lua不可用：触发法球效果时（未知）
     */
    MODIFIER_EVENT_ON_ORB_EFFECT = 215,
    /**
     * 产生攻击分裂时（例：巨力挥舞）
     */
    MODIFIER_EVENT_ON_PROCESS_CLEAVE = 216,
    /**
     * 造成伤害时（例：幽魂之剑）
     */
    MODIFIER_EVENT_ON_DAMAGE_CALCULATED = 217,
    /**
     * 造成技能伤害时（例：束手束脚）
     */
    MODIFIER_EVENT_ON_MAGIC_DAMAGE_CALCULATED = 218,
    /**
     * 攻击结束时（例：并列）
     */
    MODIFIER_EVENT_ON_ATTACKED = 219,
    /**
     * 单位死亡时（例：衰退光环）
     */
    MODIFIER_EVENT_ON_DEATH = 220,
    /**
     * 完全死亡时（例：临别一枪）
     */
    MODIFIER_EVENT_ON_DEATH_COMPLETED = 221,
    /**
     * 单位复活时（例：下地狱再上来）
     */
    MODIFIER_EVENT_ON_RESPAWN = 222,
    /**
     * 消耗魔法时（例：幽冥守卫）
     */
    MODIFIER_EVENT_ON_SPENT_MANA = 223,
    /**
     * 消耗生命时（未知）
     */
    MODIFIER_EVENT_ON_SPENT_HEALTH = 224,
    /**
     * Method Name: `OnSpentItemCharge`
     */
    MODIFIER_EVENT_ON_SPENT_ITEM_CHARGE = 225,
    /**
     * 正在传送时（例：剑刃风暴）
     */
    MODIFIER_EVENT_ON_TELEPORTING = 226,
    /**
     * 传送结束时（例：降临）
     */
    MODIFIER_EVENT_ON_TELEPORTED = 227,
    /**
     * 设定单位位置时（例：扔出）
     */
    MODIFIER_EVENT_ON_SET_LOCATION = 228,
    /**
     * 获取生命时（未知）
     */
    MODIFIER_EVENT_ON_HEALTH_GAINED = 229,
    /**
     * 获取魔法时（例：羁绊）
     */
    MODIFIER_EVENT_ON_MANA_GAINED = 230,
    /**
     * 产生击杀归属时（例：死神镰刀）
     */
    MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT = 231,
    /**
     * 击杀英雄时（例：血色外衣）
     */
    MODIFIER_EVENT_ON_HERO_KILLED = 232,
    /**
     * 获得治疗时（例：羁绊）
     */
    MODIFIER_EVENT_ON_HEAL_RECEIVED = 233,
    /**
     * Method Name: `OnRedirectHealthGain`
     */
    MODIFIER_EVENT_ON_REDIRECT_HEALTH_GAIN = 234,
    /**
     * 摧毁建筑时（例：毁灭之赏）
     */
    MODIFIER_EVENT_ON_BUILDING_KILLED = 235,
    /**
     * 模型替换时（例：古龙形态）
     */
    MODIFIER_EVENT_ON_MODEL_CHANGED = 236,
    /**
     * 施加modifier时（例：咤）
     */
    MODIFIER_EVENT_ON_MODIFIER_ADDED = 237,
    /**
     * Lua不可用：移除modifier时（例：神杖高射火炮）
     */
    MODIFIER_EVENT_ON_MODIFIER_REMOVED = 238,
    /**
     * Method Name: `OnScepterUpgradeSelected`
     */
    MODIFIER_EVENT_ON_SCEPTER_UPGRADE_SELECTED = 239,
    /**
     * Method Name: `OnShardUpgradeSelected`
     */
    MODIFIER_EVENT_ON_SHARD_UPGRADE_SELECTED = 240,
    /**
     * 技能数值说明（例：太多了）
     */
    MODIFIER_PROPERTY_TOOLTIP = 241,
    /**
     * 模型替换（例：真熊形态）
     */
    MODIFIER_PROPERTY_MODEL_CHANGE = 242,
    /**
     * 定值模型体积（例：腐朽）
     */
    MODIFIER_PROPERTY_MODEL_SCALE = 243,
    /**
     * 模型体积动画时间（未知）
     */
    MODIFIER_PROPERTY_MODEL_SCALE_ANIMATE_TIME = 244,
    /**
     * 模型体积缓入缓出动画（未知）
     */
    MODIFIER_PROPERTY_MODEL_SCALE_USE_IN_OUT_EASE = 245,
    /**
     * 模型体积覆盖（未知）
     */
    MODIFIER_PROPERTY_MODEL_SCALE_CONSTANT = 246,
    /**
     * 神杖升级（例：神杖）
     */
    MODIFIER_PROPERTY_IS_SCEPTER = 247,
    /**
     * Lua不可用：魔晶升级（例：魔晶）
     */
    MODIFIER_PROPERTY_IS_SHARD = 248,
    /**
     * Lua不可用：扫描冷却降低（例：望远镜）
     */
    MODIFIER_PROPERTY_RADAR_COOLDOWN_REDUCTION = 249,
    /**
     * 动画转变（例：太多了）
     */
    MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS = 250,
    /**
     * 攻击声音特效（例：太多了）
     */
    MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND = 251,
    /**
     * 倒计时特效（例：普通召唤单位默认）
     */
    MODIFIER_PROPERTY_LIFETIME_FRACTION = 252,
    /**
     * 模型视野（例：风雷之击）
     */
    MODIFIER_PROPERTY_PROVIDES_FOW_POSITION = 253,
    /**
     * 施放技能消耗生命值（未知）
     */
    MODIFIER_PROPERTY_SPELLS_REQUIRE_HP = 254,
    /**
     * 通过生命值施放技能（例：血魔法）
     */
    MODIFIER_PROPERTY_CONVERT_MANA_COST_TO_HEALTH_COST = 255,
    /**
     * 强制小地图显示（未知）
     */
    MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP = 256,
    /**
     * 朝向锁定（例：护身甲盾）
     */
    MODIFIER_PROPERTY_DISABLE_TURNING = 257,
    /**
     * 忽略施法角度（例：喷气背包）
     */
    MODIFIER_PROPERTY_IGNORE_CAST_ANGLE = 258,
    /**
     * 改变技能数值（未知）
     */
    MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE = 259,
    /**
     * 覆盖技能数值（例：太多了）
     */
    MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL = 260,
    /**
     * 特殊覆盖技能数值（例：太多了）
     */
    MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL_VALUE = 261,
    /**
     * 技能排布隐藏（例：感染）
     */
    MODIFIER_PROPERTY_ABILITY_LAYOUT = 262,
    /**
     * 被支配时（例：感染）
     */
    MODIFIER_EVENT_ON_DOMINATED = 263,
    /**
     * Lua不可用：击杀时（未知）
     */
    MODIFIER_EVENT_ON_KILL = 264,
    /**
     * Lua不可用：助攻时（未知）
     */
    MODIFIER_EVENT_ON_ASSIST = 265,
    /**
     * 风暴双雄克隆体标签（例：风暴双雄）
     */
    MODIFIER_PROPERTY_TEMPEST_DOUBLE = 266,
    /**
     * 模型替换时粒子特效（例：暗夜猎影）
     */
    MODIFIER_PROPERTY_PRESERVE_PARTICLES_ON_MODEL_CHANGE = 267,
    /**
     * 攻击完成时（例：强化图腾）
     */
    MODIFIER_EVENT_ON_ATTACK_FINISHED = 268,
    /**
     * Lua不可用：忽略冷却（未知）
     */
    MODIFIER_PROPERTY_IGNORE_COOLDOWN = 269,
    /**
     * 可攻击树木（未知）
     */
    MODIFIER_PROPERTY_CAN_ATTACK_TREES = 270,
    /**
     * 设置飞行高度（例：丛林之舞）
     */
    MODIFIER_PROPERTY_VISUAL_Z_DELTA = 271,
    /**
     * 起飞速度覆盖（未知）
     */
    MODIFIER_PROPERTY_VISUAL_Z_SPEED_BASE_OVERRIDE = 272,
    /**
     * Lua不可用：幻象承受伤害调整（例：幻象默认）
     */
    MODIFIER_PROPERTY_INCOMING_DAMAGE_ILLUSION = 273,
    /**
     * 不使攻击目标暴露（未知）
     */
    MODIFIER_PROPERTY_DONT_GIVE_VISION_OF_ATTACKER = 274,
    /**
     * 状态栏即时更新说明（例：太多了）
     */
    MODIFIER_PROPERTY_TOOLTIP2 = 275,
    /**
     * 攻击记录摧毁时（例：奥术天球）
     */
    MODIFIER_EVENT_ON_ATTACK_RECORD_DESTROY = 276,
    /**
     * 弹道被摧毁时（例：热血竞技场）
     */
    MODIFIER_EVENT_ON_PROJECTILE_OBSTRUCTION_HIT = 277,
    /**
     * 跳过传送（未知）
     */
    MODIFIER_PROPERTY_SUPPRESS_TELEPORT = 278,
    /**
     * 攻击取消时（例：神枪在手）
     */
    MODIFIER_EVENT_ON_ATTACK_CANCELLED = 279,
    /**
     * Lua不可用：不触发攻击分裂（例：神之谴戒）
     */
    MODIFIER_PROPERTY_SUPPRESS_CLEAVE = 280,
    /**
     * Lua不可用：机器人额外分数（未知）
     */
    MODIFIER_PROPERTY_BOT_ATTACK_SCORE_BONUS = 281,
    /**
     * 百分比减攻速调整（未知）
     */
    MODIFIER_PROPERTY_ATTACKSPEED_REDUCTION_PERCENTAGE = 282,
    /**
     * 百分比减移速调整（未知）
     */
    MODIFIER_PROPERTY_MOVESPEED_REDUCTION_PERCENTAGE = 283,
    /**
     * Lua不可用：可在移动时攻击（例：集中火力）
     */
    MODIFIER_PROPERTY_ATTACK_WHILE_MOVING_TARGET = 284,
    /**
     * 百分比攻击速度（例：长大）
     */
    MODIFIER_PROPERTY_ATTACKSPEED_PERCENTAGE = 285,
    /**
     * Lua不可用：尝试躲避弹道时（未知）
     */
    MODIFIER_EVENT_ON_ATTEMPT_PROJECTILE_DODGE = 286,
    /**
     * 特殊百分比冷却缩减（未知）
     */
    MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING = 287,
    /**
     * Lua不可用：技能共享目标（例：位面空洞）
     */
    MODIFIER_PROPERTY_SPELL_REDIRECT_TARGET = 288,
    /**
     * Lua不可用：定值转身速率（例：织网）
     */
    MODIFIER_PROPERTY_TURN_RATE_CONSTANT = 289,
    /**
     * Lua不可用：中立物品栏可使用普通物品（例：囤积狂鼠）
     */
    MODIFIER_PROPERTY_PACK_RAT = 290,
    /**
     * Lua不可用：施加方百分比物理伤害（例：怨灵之契）
     */
    MODIFIER_PROPERTY_PHYSICALDAMAGEOUTGOING_PERCENTAGE = 291,
    /**
     * Lua不可用：击退抗性（例：坚固核心）
     */
    MODIFIER_PROPERTY_KNOCKBACK_AMPLIFICATION_PERCENTAGE = 292,
    /**
     * 特殊生命条（例：攻击次数型单位）
     */
    MODIFIER_PROPERTY_HEALTHBAR_PIPS = 293,
    /**
     * 全类型伤害护盾（例：无光之盾）
     */
    MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT = 294,
    /**
     * 施法成功时（例：绝刃）
     */
    MODIFIER_EVENT_SPELL_APPLIED_SUCCESSFULLY = 295,
    /**
     * 尾端伤害无效化（例：虚妄之诺）
     */
    MODIFIER_PROPERTY_AVOID_DAMAGE_AFTER_REDUCTIONS = 296,
    /**
     * Lua不可用：致使攻击失败（例：林渊旅人）
     */
    MODIFIER_PROPERTY_FAIL_ATTACK = 297,
    /**
     * Lua不可用：前结算伤害调整（未知）
     */
    MODIFIER_PROPERTY_PREREDUCE_INCOMING_DAMAGE_MULT = 298,
    /**
     * 跳过死亡特效（未知）
     */
    MODIFIER_PROPERTY_SUPPRESS_FULLSCREEN_DEATH_FX = 299,
    /**
     * Lua不可用：后结算伤害护盾（未知）
     */
    MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT_POST = 300,
    /**
     * Lua不可用：特殊百分比总攻击调整（例：窒碍短匕）
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_MULTIPLICATIVE = 301,
    /**
     * Lua不可用：被动金钱倍率（例：贤者石）
     */
    MODIFIER_PROPERTY_TICK_GOLD_MULTIPLIER = 302,
    /**
     * Lua不可用：特殊减速抗性（例：散华）
     */
    MODIFIER_PROPERTY_SLOW_RESISTANCE_UNIQUE = 303,
    /**
     * Lua不可用：减速抗性（例：神之力量）
     */
    MODIFIER_PROPERTY_SLOW_RESISTANCE_STACKING = 304,
    /**
     * Lua不可用：减速抗性影响攻速（例：不可逾越）
     */
    MODIFIER_PROPERTY_SLOW_RESISTANCE_APPLIES_TO_ATTACKS = 305,
    /**
     * Lua不可用：百分比作用范围加成（例：凶）
     */
    MODIFIER_PROPERTY_AOE_BONUS_PERCENTAGE = 306,
    /**
     * Lua不可用：区域百分比弹道速度（例：逆转时空）
     */
    MODIFIER_PROPERTY_PROJECTILE_SPEED = 307,
    /**
     * Lua不可用：区域百分比目标弹道速度（未知）
     */
    MODIFIER_PROPERTY_PROJECTILE_SPEED_TARGET = 308,
    /**
     * Lua不可用：变为力量（例：潮落）
     */
    MODIFIER_PROPERTY_BECOME_STRENGTH = 309,
    /**
     * Lua不可用：变为敏捷（例：潮涨）
     */
    MODIFIER_PROPERTY_BECOME_AGILITY = 310,
    /**
     * Lua不可用：变为智力（未知）
     */
    MODIFIER_PROPERTY_BECOME_INTELLIGENCE = 311,
    /**
     * Lua不可用：变为全才（例：老版冥界亚龙天赋）
     */
    MODIFIER_PROPERTY_BECOME_UNIVERSAL = 312,
    /**
     * Lua不可用：强制触发魔棒时（例：马蹄践踏）
     */
    MODIFIER_EVENT_ON_FORCE_PROC_MAGIC_STICK = 313,
    /**
     * 生命移除时（未知）
     */
    MODIFIER_EVENT_ON_DAMAGE_HPLOSS = 314,
    /**
     * 智慧神龛共享（例：古龙学者）
     */
    MODIFIER_PROPERTY_SHARE_XPRUNE = 315,
    /**
     * 智慧神龛冷却时间覆盖（未知）
     */
    MODIFIER_PROPERTY_XP_FOUNTAIN_COUNTDOWN_TIME_OVERRIDE = 316,
    /**
     * 死亡无回城卷轴（未知）
     */
    MODIFIER_PROPERTY_NO_FREE_TP_SCROLL_ON_DEATH = 317,
    /**
     * Lua不可用：额外中立物品选项（例：三只手）
     */
    MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_CHOICE = 318,
    /**
     * Method Name: `HasBonusNeutralItemPassive`
     */
    MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_PASSIVE = 319,
    /**
     * Lua不可用：中立附魔累加（例：斯布恩的藏品）
     */
    MODIFIER_PROPERTY_PRESERVE_NEUTRAL_ITEM_PASSIVES = 320,
    /**
     * Lua不可用：最大生命值设定（例：坚毅之件）
     */
    MODIFIER_PROPERTY_FORCE_MAX_HEALTH = 321,
    /**
     * Lua不可用：最大魔法值设定（例：血魔法）
     */
    MODIFIER_PROPERTY_FORCE_MAX_MANA = 322,
    /**
     * Lua不可用：特殊定值作用范围加成（例：缚灵索）
     */
    MODIFIER_PROPERTY_AOE_BONUS_CONSTANT = 323,
    /**
     * Lua不可用：定值作用范围加成（例：亵渎之力）
     */
    MODIFIER_PROPERTY_AOE_BONUS_CONSTANT_STACKING = 324,
    /**
     * Lua不可用：在首端伤害格挡前时（例：永世法衣）
     */
    MODIFIER_EVENT_ON_TAKEDAMAGE_POST_UNAVOIDABLE_BLOCK = 325,
    /**
     * Lua不可用：锁闭伤害技能时（例：闪烁匕首）
     */
    MODIFIER_EVENT_ON_MUTE_DAMAGE_ABILITIES = 326,
    /**
     * Lua不可用：不触发致命一击（例：老版英灵胸针）
     */
    MODIFIER_PROPERTY_SUPPRESS_CRIT = 327,
    /**
     * Lua不可用：提供技能点数（例：曲线学习）
     */
    MODIFIER_PROPERTY_ABILITY_POINTS = 328,
    /**
     * Lua不可用：百分比买活惩罚（例：恶魔的交易）
     */
    MODIFIER_PROPERTY_BUYBACK_PENALTY_PERCENT = 329,
    /**
     * Lua不可用：百分比出售价格增加（例：恶魔的交易）
     */
    MODIFIER_PROPERTY_ITEM_SELLBACK_COST = 330,
    /**
     * 可拆分任意物品（例：拆东补西）
     */
    MODIFIER_PROPERTY_DISASSEMBLE_ANYTHING = 331,
    /**
     * 固定魔法恢复（例：死亡充能）
     */
    MODIFIER_PROPERTY_FIXED_MANA_REGEN = 332,
    /**
     * Lua不可用：上下坡落空概率加成（例：制高点）
     */
    MODIFIER_PROPERTY_BONUS_UPHILL_MISS_CHANCE = 333,
    /**
     * Lua不可用：反补生命百分比调整（例：盛宴）
     */
    MODIFIER_PROPERTY_CREEP_DENY_PERCENT = 334,
    /**
     * 绝对攻速上限设定（未知）
     */
    MODIFIER_PROPERTY_ATTACKSPEED_ABSOLUTE_MAX = 335,
    /**
     * Lua不可用：更改视野阵营（例：热血运动）
     */
    MODIFIER_PROPERTY_FOW_TEAM = 336,
    /**
     * 开始死亡时（例：驱邪护符）
     */
    MODIFIER_EVENT_ON_HERO_BEGIN_DYING = 337,
    /**
     * Lua不可用：疗伤莲花效果增强（例：赛洛蒙妮的信徒）
     */
    MODIFIER_PROPERTY_BONUS_LOTUS_HEAL = 338,
    /**
     * Lua不可用：百分比力量生命恢复增强（例：内在优势）
     */
    MODIFIER_PROPERTY_BASE_HP_REGEN_PER_STR_BONUS_PERCENTAGE = 339,
    /**
     * Lua不可用：百分比敏捷护甲增强（例：内在优势）
     */
    MODIFIER_PROPERTY_BASE_ARMOR_PER_AGI_BONUS_PERCENTAGE = 340,
    /**
     * Method Name: `GetModifierBaseAttackSpeedPerAgiBonusPercentage`
     */
    MODIFIER_PROPERTY_BASE_ATTACKSPEED_PER_AGI_BONUS_PERCENTAGE = 341,
    /**
     * Lua不可用：百分比智力生命恢复增强（例：内在优势）
     */
    MODIFIER_PROPERTY_BASE_MP_REGEN_PER_INT_BONUS_PERCENTAGE = 342,
    /**
     * Lua不可用：百分比智力魔法抗性增强（例：内在优势）
     */
    MODIFIER_PROPERTY_BASE_MRES_PER_INT_BONUS_PERCENTAGE = 343,
    /**
     * 进入白天时（例：辰星破晓）
     */
    MODIFIER_EVENT_ON_DAY_STARTED = 344,
    /**
     * Lua不可用：进入夜晚时（例：固有增益）
     */
    MODIFIER_EVENT_ON_NIGHT_STARTED = 345,
    /**
     * 额外幻象产生概率（例：混沌称霸）
     */
    MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_CHANCE = 346,
    /**
     * 额外幻象产生数量（例：混沌称霸）
     */
    MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_COUNT = 347,
    /**
     * Lua不可用：伪随机概率减低（例：天佑勇者）
     */
    MODIFIER_PROPERTY_PSEUDORANDOM_BONUS = 348,
    /**
     * 攻击弹道交互高度增加（例：冰川）
     */
    MODIFIER_PROPERTY_ATTACK_HEIGHT_BONUS = 349,
    /**
     * Lua不可用：跳过攻击结算（例：死亡守卫）
     */
    MODIFIER_PROPERTY_SKIP_ATTACK_REGULATOR = 350,
    /**
     * Lua不可用：目标致盲（例：老版烟幕）
     */
    MODIFIER_PROPERTY_MISS_PERCENTAGE_TARGET = 351,
    /**
     * 额外掉落中立物品（例：丛林赠品）
     */
    MODIFIER_PROPERTY_ADDITIONAL_NEUTRAL_ITEM_DROPS = 352,
    /**
     * 额外百分比终结连杀金钱（例：职业猎人）
     */
    MODIFIER_PROPERTY_KILL_STREAK_BONUS_GOLD_PERCENTAGE = 353,
    /**
     * Lua不可用：生命恢复系数（例：无畏）
     */
    MODIFIER_PROPERTY_HP_REGEN_MULTIPLIER_PRE_AMPLIFICATION = 354,
    /**
     * Lua不可用：命石覆盖（例：变形）
     */
    MODIFIER_PROPERTY_HEROFACET_OVERRIDE = 355,
    /**
     * 摧毁树木时（例：暴露疗法）
     */
    MODIFIER_EVENT_ON_TREE_CUT_DOWN = 356,
    /**
     * Lua不可用：攻击分裂命中时（例：死亡之拳）
     */
    MODIFIER_EVENT_ON_CLEAVE_ATTACK_LANDED = 357,
    /**
     * Lua不可用：最低属性等级（例：虚空行者）
     */
    MODIFIER_PROPERTY_MIN_ATTRIBUTE_LEVEL = 358,
    /**
     * Lua不可用：中立物品复制（例：英熊好礼）
     */
    MODIFIER_PROPERTY_TIER_TOKEN_REROLL = 359,
    /**
     * Lua不可用：视野角度限制（例：红光满面）
     */
    MODIFIER_PROPERTY_VISION_DEGREES_RESTRICTION = 360,
    /**
     * Lua不可用：叠加末端伤害格挡（例：幽灵船）
     */
    MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_STACKING = 361,
    /**
     * Lua不可用：物品栏限制（例：熊亦求精）
     */
    MODIFIER_PROPERTY_INVENTORY_SLOT_RESTRICTED = 362,
    /**
     * Lua不可用：同步中立物品时（例：英熊好礼）
     */
    MODIFIER_EVENT_ON_TIER_TOKEN_REROLLED = 363,
    /**
     * 技能共享（例：缚魂）
     */
    MODIFIER_PROPERTY_REDIRECT_SPELL = 364,
    /**
     * Lua不可用：活跃基础攻击力（例：灵幻兵械）
     */
    MODIFIER_PROPERTY_BASEATTACK_POSTBONUS = 365,
    /**
     * Lua不可用：视野所属阵营改变时（例：真实视域）
     */
    MODIFIER_EVENT_ON_FOW_TEAM_CHANGED = 366,
    /**
     * Lua不可用：跳过攻击触发（未知）
     */
    MODIFIER_PROPERTY_SUPPRESS_ATTACK_PROCS = 367,
    /**
     * Lua不可用：切换开关技能时（例：熊亦求精）
     */
    MODIFIER_EVENT_ON_ABILITY_TOGGLED = 368,
    /**
     * Lua不可用：不触发攻击特效（例：翔影之钗）
     */
    MODIFIER_PROPERTY_AVOID_ATTACK_PROCS = 369,
    /**
     * Lua不可用：神符产生时（未知）
     */
    MODIFIER_EVENT_ON_RUNE_SPAWN = 370,
    /**
     * Lua不可用：攻击吸血（例：撒旦之邪力）
     */
    MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL = 371,
    /**
     * Lua不可用：技能吸血（例：血精石）
     */
    MODIFIER_PROPERTY_MAGICAL_LIFESTEAL = 372,
    /**
     * Lua不可用：造成纯粹伤害时（例：束手束脚）
     */
    MODIFIER_EVENT_ON_PURE_DAMAGE_CALCULATED = 373,
    /**
     * Lua不可用：提前打造中立物品（例：基本法则锻造）
     */
    MODIFIER_EVENT_NEUTRAL_TRINKET_OPTIONS = 374,
    /**
     * Lua不可用：选择中立附魔时（未知）
     */
    MODIFIER_EVENT_NEUTRAL_ENHANCEMENT_OPTIONS = 375,
    /**
     * 定值标准移速上限（例：奔流湍急）
     */
    MODIFIER_PROPERTY_MOVESPEED_MAX_BONUS_CONSTANT = 376,
    /**
     * 后移速调整定值移速（例：奔流湍急）
     */
    MODIFIER_PROPERTY_MOVESPEED_POST_MULTIPLIER_BONUS_CONSTANT = 377,
    /**
     * Lua不可用：禁止产生幻象（未知）
     */
    MODIFIER_PROPERTY_FORBID_ILLUSIONS = 378,
    /**
     * Lua不可用：魔法消耗覆盖（未知）
     */
    MODIFIER_PROPERTY_MANACOST_OVERRIDE = 379,
    /**
     * Lua不可用：生命回复调整（例：斯嘉蒂之眼）
     */
    MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION = 380,
    /**
     * Lua不可用：特殊生命回复调整（例：散华）
     */
    MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION_UNIQUE = 381,
    /**
     * Lua不可用：特殊施加方治疗调整（未知）
     */
    MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE_UNIQUE = 382,
    /**
     * Method Name: `GetModifierPropertyRedirectHealthGain`
     */
    MODIFIER_PROPERTY_REDIRECT_HEALTH_GAIN = 383,
    /**
     * Lua不可用：跳过承受方致命一击（未知）
     */
    MODIFIER_PROPERTY_SUPPRESS_INCOMING_CRIT = 384,
    /**
     * Lua不可用：中立物品升级（例：休眠珍品）
     */
    MODIFIER_PROPERTY_UPGRADE_NEUTRAL_ARTIFACTS = 385,
    /**
     * Lua不可用：忽略无效攻击移动指令（未知）
     */
    MODIFIER_PROPERTY_SUPPRESS_INVALID_MOVE_ATTACK_ORDERS = 386,
    /**
     * Lua不可用：消耗品加速（例：源泉）
     */
    MODIFIER_PROPERTY_CONSUMABLE_USE_SPEED = 387,
    /**
     * Lua不可用：首次学习等级调整（例：曲线学习）
     */
    MODIFIER_PROPERTY_REQUIRED_LEVEL = 388,
    /**
     * Lua不可用：刷新modifier时（例：安可）
     */
    MODIFIER_EVENT_ON_MODIFIER_REFRESHED = 389,
    /**
     * Lua不可用：交换技能时（例：两栖狂想曲）
     */
    MODIFIER_EVENT_ON_ABILITY_SWAPPED = 390,
    /**
     * Lua不可用：小兵击杀金钱覆盖（例：加重骰子）
     */
    MODIFIER_PROPERTY_OVERRIDE_CREEP_BOUNTY = 391,
    /**
     * Lua不可用：基础攻击力覆盖（例：加重骰子）
     */
    MODIFIER_PROPERTY_OVERRIDE_BASE_DAMAGE = 392,
    /**
     * Method Name: `GetModifierOverrideUntargetableFrom`
     */
    MODIFIER_PROPERTY_UNTARGETABLE_FROM = 393,
    /**
     * Method Name: `GetModifierOverrideUntargetableTo`
     */
    MODIFIER_PROPERTY_UNTARGETABLE_TO = 394,
    /**
     * Method Name: `GetModifierSuperIllusionWithItems`
     */
    MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ITEMS = 395,
    /**
     * Method Name: `OnPurged`
     */
    MODIFIER_EVENT_ON_PURGE = 396,
    /**
     * Method Name: `OnIllusionCreated`
     */
    MODIFIER_EVENT_ON_ILLUSION_CREATED = 397,
    /**
     * Method Name: `GetModifierHeroLevelScale`
     */
    MODIFIER_PROPERTY_HEROLEVELSCALE = 398,
    MODIFIER_FUNCTION_LAST = 399,
    MODIFIER_FUNCTION_INVALID = 65535,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ModifierState = modifierstate;

declare enum modifierstate {
    /**
     * 缠绕（例：疯狂生长）
     */ MODIFIER_STATE_ROOTED = 0,
    /**
     * 缴械（例：超震声波）
     */
    MODIFIER_STATE_DISARMED = 1,
    /**
     * 攻击免疫（例：幽魂权杖）
     */
    MODIFIER_STATE_ATTACK_IMMUNE = 2,
    /**
     * 沉默（例：全领域静默）
     */
    MODIFIER_STATE_SILENCED = 3,
    /**
     * 锁闭（例：神杖静态风暴）
     */
    MODIFIER_STATE_MUTED = 4,
    /**
     * 眩晕（例：魔法箭）
     */
    MODIFIER_STATE_STUNNED = 5,
    /**
     * 妖术（例：邪恶镰刀）
     */
    MODIFIER_STATE_HEXED = 6,
    /**
     * 隐身（例：暗影步）
     */
    MODIFIER_STATE_INVISIBLE = 7,
    /**
     * 无敌（例：海妖之歌）
     */
    MODIFIER_STATE_INVULNERABLE = 8,
    /**
     * 技能免疫（例：技能免疫）
     */
    MODIFIER_STATE_MAGIC_IMMUNE = 9,
    /**
     * 共享视野（例：静电连接）
     */
    MODIFIER_STATE_PROVIDES_VISION = 10,
    /**
     * 睡眠（例：噩梦）
     */
    MODIFIER_STATE_NIGHTMARED = 11,
    /**
     * 禁用物理伤害格挡（未知）
     */
    MODIFIER_STATE_BLOCK_DISABLED = 12,
    /**
     * 禁用闪避（未知）
     */
    MODIFIER_STATE_EVADE_DISABLED = 13,
    /**
     * 无法选中（例：无影拳）
     */
    MODIFIER_STATE_UNSELECTABLE = 14,
    /**
     * 无法指定敌方目标（未知）
     */
    MODIFIER_STATE_CANNOT_TARGET_ENEMIES = 15,
    /**
     * 无法指定建筑目标（例：越界）
     */
    MODIFIER_STATE_CANNOT_TARGET_BUILDINGS = 16,
    /**
     * 克敌机先（例：复仇）
     */
    MODIFIER_STATE_CANNOT_MISS = 17,
    /**
     * 可被反补（例：瘴气）
     */
    MODIFIER_STATE_SPECIALLY_DENIABLE = 18,
    /**
     * 动作冻结（例：急速冷却）
     */
    MODIFIER_STATE_FROZEN = 19,
    /**
     * 无法行动（例：巫毒变身术）
     */
    MODIFIER_STATE_COMMAND_RESTRICTED = 20,
    /**
     * 隐藏小地图图标（例：虫群）
     */
    MODIFIER_STATE_NOT_ON_MINIMAP = 21,
    /**
     * 低攻击优先级（例：七十二变）
     */
    MODIFIER_STATE_LOW_ATTACK_PRIORITY = 22,
    /**
     * 隐藏单位生命条（例：信使护盾）
     */
    MODIFIER_STATE_NO_HEALTH_BAR = 23,
    /**
     * 对敌隐藏单位生命条（例：魅影无形）
     */
    MODIFIER_STATE_NO_HEALTH_BAR_FOR_ENEMIES = 24,
    /**
     * 对其他玩家隐藏生命条（例：虚无投影）
     */
    MODIFIER_STATE_NO_HEALTH_BAR_FOR_OTHER_PLAYERS = 25,
    /**
     * 飞行（例：黑暗飞升）
     */
    MODIFIER_STATE_FLYING = 26,
    /**
     * 相位状态（例：守卫冲刺）
     */
    MODIFIER_STATE_NO_UNIT_COLLISION = 27,
    /**
     * 无法作为跟随目标（例：幻影之拥）
     */
    MODIFIER_STATE_NO_TEAM_MOVE_TO = 28,
    /**
     * 选择组忽略置入（例：幻影之拥）
     */
    MODIFIER_STATE_NO_TEAM_SELECT = 29,
    /**
     * 破坏（例：蝮蛇突袭）
     */
    MODIFIER_STATE_PASSIVES_DISABLED = 30,
    /**
     * 被支配标记（例：支配头盔）
     */
    MODIFIER_STATE_DOMINATED = 31,
    /**
     * 失去视野（例：诱敌奇术）
     */
    MODIFIER_STATE_BLIND = 32,
    /**
     * 隐藏（例：崩裂禁锢）
     */
    MODIFIER_STATE_OUT_OF_GAME = 33,
    /**
     * 虚拟友方（例：感染）
     */
    MODIFIER_STATE_FAKE_ALLY = 34,
    /**
     * 无视地形状态（例：幽鬼之刃）
     */
    MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY = 35,
    /**
     * 真实视域免疫（例：暗影之舞）
     */
    MODIFIER_STATE_TRUESIGHT_IMMUNE = 36,
    /**
     * 不取对象（例：便车）
     */
    MODIFIER_STATE_UNTARGETABLE = 37,
    /**
     * 友方不取对象（例：魔晶烟幕）
     */
    MODIFIER_STATE_UNTARGETABLE_ALLIED = 38,
    /**
     * 敌方不取对象（例：暗影之境）
     */
    MODIFIER_STATE_UNTARGETABLE_ENEMY = 39,
    /**
     * 自身不取对象（未知）
     */
    MODIFIER_STATE_UNTARGETABLE_SELF = 40,
    /**
     * 无法执行移动攻击（例：掘地）
     */
    MODIFIER_STATE_IGNORING_MOVE_AND_ATTACK_ORDERS = 41,
    /**
     * 树木穿行（例：自然蔽护）
     */
    MODIFIER_STATE_ALLOW_PATHING_THROUGH_TREES = 42,
    /**
     * 对敌隐藏小地图图标（例：魅影无形）
     */
    MODIFIER_STATE_NOT_ON_MINIMAP_FOR_ENEMIES = 43,
    /**
     * 无视减速（例：弹无虚发）
     */
    MODIFIER_STATE_UNSLOWABLE = 44,
    /**
     * 束缚（例：突袭）
     */
    MODIFIER_STATE_TETHERED = 45,
    /**
     * 无法执行停止命令（例：星破天惊）
     */
    MODIFIER_STATE_IGNORING_STOP_ORDERS = 46,
    /**
     * 恐惧（例：恐吓）
     */
    MODIFIER_STATE_FEARED = 47,
    /**
     * 嘲讽（例：狂战士的怒吼）
     */
    MODIFIER_STATE_TAUNTED = 48,
    /**
     * 强制位移免疫（例：捶）
     */
    MODIFIER_STATE_CANNOT_BE_MOTION_CONTROLLED = 49,
    /**
     * 飞行视野（例：喷气背包）
     */
    MODIFIER_STATE_FORCED_FLYING_VISION = 50,
    /**
     * 可攻击友方（未知）
     */
    MODIFIER_STATE_ATTACK_ALLIES = 51,
    /**
     * 仅无视地形（未知）
     */
    MODIFIER_STATE_ALLOW_PATHING_THROUGH_CLIFFS = 52,
    MODIFIER_STATE_ALLOW_PATHING_THROUGH_POWER_COGS = 53,
    /**
     * 无法被反补（未知）
     */
    MODIFIER_STATE_SPECIALLY_UNDENIABLE = 54,
    /**
     * 无视特殊地形（未知）
     */
    MODIFIER_STATE_ALLOW_PATHING_THROUGH_OBSTRUCTIONS = 55,
    /**
     * 减益免疫（例：剑刃风暴）
     */
    MODIFIER_STATE_DEBUFF_IMMUNE = 56,
    /**
     * 穿越守护者之门（例：守护者之门）
     */
    MODIFIER_STATE_ALLOW_PATHING_THROUGH_BASE_BLOCKER = 57,
    /**
     * 无法执行移动命令（未知）
     */
    MODIFIER_STATE_IGNORING_MOVE_ORDERS = 58,
    /**
     * 远程近战结算（例：灵魂打击）
     */
    MODIFIER_STATE_ATTACKS_ARE_MELEE = 59,
    /**
     * 完全启动背包（例：老版斯布恩的藏品）
     */
    MODIFIER_STATE_CAN_USE_BACKPACK_ITEMS = 60,
    /**
     * 持续施法期间施法（例：湮灭专家）
     */
    MODIFIER_STATE_CASTS_IGNORE_CHANNELING = 61,
    /**
     * 攻击不曝露（例：吉利服）
     */
    MODIFIER_STATE_ATTACKS_DONT_REVEAL = 62,
    /**
     * 无野怪仇恨（例：丛林之舞）
     */
    MODIFIER_STATE_NEUTRALS_DONT_ATTACK = 63,
    /**
     * 终止占位（默认）
     */
    MODIFIER_STATE_LAST = 64,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ModifierAttribute = DOTAModifierAttribute_t;

declare enum DOTAModifierAttribute_t {
    /**
     * 无特殊属性（默认）
     */ MODIFIER_ATTRIBUTE_NONE = 0,
    /**
     * 永久状态（例：冰）
     */
    MODIFIER_ATTRIBUTE_PERMANENT = 1,
    /**
     * 独立结算（例：沸血之矛）
     */
    MODIFIER_ATTRIBUTE_MULTIPLE = 2,
    /**
     * 可对无敌单位生效（例：衰退光环）
     */
    MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE = 4,
    /**
     * 光环优先级（未知）
     */
    MODIFIER_ATTRIBUTE_AURA_PRIORITY = 8,
    /**
     * 忽略躲避（未知）
     */
    MODIFIER_ATTRIBUTE_IGNORE_DODGE = 16,
    /**
     * 可被复制（未知）
     */
    MODIFIER_ATTRIBUTE_DUPLICATED = 32,
}

declare enum Attributes {
    DOTA_ATTRIBUTE_STRENGTH = 0,
    DOTA_ATTRIBUTE_AGILITY = 1,
    DOTA_ATTRIBUTE_INTELLECT = 2,
    DOTA_ATTRIBUTE_ALL = 3,
    DOTA_ATTRIBUTE_MAX = 4,
    DOTA_ATTRIBUTE_INVALID = -1,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ParticleAttachment = ParticleAttachment_t;

declare enum ParticleAttachment_t {
    PATTACH_INVALID = -1,
    PATTACH_ABSORIGIN = 0,
    PATTACH_ABSORIGIN_FOLLOW = 1,
    PATTACH_CUSTOMORIGIN = 2,
    PATTACH_CUSTOMORIGIN_FOLLOW = 3,
    PATTACH_POINT = 4,
    PATTACH_POINT_FOLLOW = 5,
    PATTACH_EYES_FOLLOW = 6,
    PATTACH_OVERHEAD_FOLLOW = 7,
    PATTACH_WORLDORIGIN = 8,
    PATTACH_ROOTBONE_FOLLOW = 9,
    PATTACH_RENDERORIGIN_FOLLOW = 10,
    PATTACH_MAIN_VIEW = 11,
    PATTACH_WATERWAKE = 12,
    PATTACH_CENTER_FOLLOW = 13,
    PATTACH_CUSTOM_GAME_STATE_1 = 14,
    PATTACH_HEALTHBAR = 15,
    MAX_PATTACH_TYPES = 16,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type MotionControllerPriority = DOTA_MOTION_CONTROLLER_PRIORITY;

declare enum DOTA_MOTION_CONTROLLER_PRIORITY {
    DOTA_MOTION_CONTROLLER_PRIORITY_LOWEST = 0,
    DOTA_MOTION_CONTROLLER_PRIORITY_LOW = 1,
    DOTA_MOTION_CONTROLLER_PRIORITY_MEDIUM = 2,
    DOTA_MOTION_CONTROLLER_PRIORITY_HIGH = 3,
    DOTA_MOTION_CONTROLLER_PRIORITY_HIGHEST = 4,
    DOTA_MOTION_CONTROLLER_PRIORITY_ULTRA = 5,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type SpeechType = DOTASpeechType_t;

declare enum DOTASpeechType_t {
    DOTA_SPEECH_USER_INVALID = 0,
    DOTA_SPEECH_USER_SINGLE = 1,
    DOTA_SPEECH_USER_TEAM = 2,
    DOTA_SPEECH_USER_TEAM_NEARBY = 3,
    DOTA_SPEECH_USER_NEARBY = 4,
    DOTA_SPEECH_USER_ALL = 5,
    DOTA_SPEECH_GOOD_TEAM = 6,
    DOTA_SPEECH_BAD_TEAM = 7,
    DOTA_SPEECH_SPECTATOR = 8,
    DOTA_SPEECH_USER_TEAM_NOSPECTATOR = 9,
    DOTA_SPEECH_RECIPIENT_TYPE_MAX = 10,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type AbilitySpeakTrigger = DOTAAbilitySpeakTrigger_t;

declare enum DOTAAbilitySpeakTrigger_t {
    DOTA_ABILITY_SPEAK_START_ACTION_PHASE = 0,
    DOTA_ABILITY_SPEAK_CAST = 1,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type CustomUiType = DotaCustomUIType_t;

declare enum DotaCustomUIType_t {
    DOTA_CUSTOM_UI_TYPE_HUD = 0,
    DOTA_CUSTOM_UI_TYPE_HERO_SELECTION = 1,
    DOTA_CUSTOM_UI_TYPE_PREGAME_STRATEGY = 2,
    DOTA_CUSTOM_UI_TYPE_GAME_INFO = 3,
    DOTA_CUSTOM_UI_TYPE_GAME_SETUP = 4,
    DOTA_CUSTOM_UI_TYPE_FLYOUT_SCOREBOARD = 5,
    DOTA_CUSTOM_UI_TYPE_HUD_TOP_BAR = 6,
    DOTA_CUSTOM_UI_TYPE_END_SCREEN = 7,
    DOTA_CUSTOM_UI_TYPE_COUNT = 8,
    DOTA_CUSTOM_UI_TYPE_INVALID = -1,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type DefaultUiElement = DotaDefaultUIElement_t;

declare enum DotaDefaultUIElement_t {
    DOTA_DEFAULT_UI_INVALID = -1,
    DOTA_DEFAULT_UI_TOP_TIMEOFDAY = 0,
    DOTA_DEFAULT_UI_TOP_HEROES = 1,
    DOTA_DEFAULT_UI_FLYOUT_SCOREBOARD = 2,
    DOTA_DEFAULT_UI_ACTION_PANEL = 3,
    DOTA_DEFAULT_UI_ACTION_MINIMAP = 4,
    DOTA_DEFAULT_UI_INVENTORY_PANEL = 5,
    DOTA_DEFAULT_UI_INVENTORY_SHOP = 6,
    DOTA_DEFAULT_UI_INVENTORY_ITEMS = 7,
    DOTA_DEFAULT_UI_INVENTORY_QUICKBUY = 8,
    DOTA_DEFAULT_UI_INVENTORY_COURIER = 9,
    DOTA_DEFAULT_UI_INVENTORY_PROTECT = 10,
    DOTA_DEFAULT_UI_INVENTORY_GOLD = 11,
    DOTA_DEFAULT_UI_SHOP_SUGGESTEDITEMS = 12,
    DOTA_DEFAULT_UI_SHOP_COMMONITEMS = 13,
    DOTA_DEFAULT_UI_HERO_SELECTION_TEAMS = 14,
    DOTA_DEFAULT_UI_HERO_SELECTION_GAME_NAME = 15,
    DOTA_DEFAULT_UI_HERO_SELECTION_CLOCK = 16,
    DOTA_DEFAULT_UI_HERO_SELECTION_HEADER = 17,
    DOTA_DEFAULT_UI_TOP_MENU_BUTTONS = 18,
    DOTA_DEFAULT_UI_TOP_BAR_BACKGROUND = 19,
    DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM = 20,
    DOTA_DEFAULT_UI_TOP_BAR_DIRE_TEAM = 21,
    DOTA_DEFAULT_UI_TOP_BAR_SCORE = 22,
    DOTA_DEFAULT_UI_ENDGAME = 23,
    DOTA_DEFAULT_UI_ENDGAME_CHAT = 24,
    DOTA_DEFAULT_UI_QUICK_STATS = 25,
    DOTA_DEFAULT_UI_PREGAME_STRATEGYUI = 26,
    DOTA_DEFAULT_UI_KILLCAM = 27,
    DOTA_DEFAULT_UI_FIGHT_RECAP = 28,
    DOTA_DEFAULT_UI_TOP_BAR = 29,
    DOTA_DEFAULT_UI_CUSTOMUI_BEHIND_HUD_ELEMENTS = 30,
    DOTA_DEFAULT_UI_AGHANIMS_STATUS = 31,
    DOTA_DEFAULT_UI_ELEMENT_COUNT = 32,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type PlayerUltimateStateOrTime = PlayerUltimateStateOrTime_t;

declare enum PlayerUltimateStateOrTime_t {
    PLAYER_ULTIMATE_STATE_READY = 0,
    PLAYER_ULTIMATE_STATE_NO_MANA = -1,
    PLAYER_ULTIMATE_STATE_NOT_LEVELED = -2,
    PLAYER_ULTIMATE_STATE_HIDDEN = -3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type PlayerOrderIssuer = PlayerOrderIssuer_t;

declare enum PlayerOrderIssuer_t {
    DOTA_ORDER_ISSUER_SELECTED_UNITS = 0,
    DOTA_ORDER_ISSUER_CURRENT_UNIT_ONLY = 1,
    DOTA_ORDER_ISSUER_HERO_ONLY = 2,
    DOTA_ORDER_ISSUER_PASSED_UNIT_ONLY = 3,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type OrderQueueBehavior = OrderQueueBehavior_t;

declare enum OrderQueueBehavior_t {
    DOTA_ORDER_QUEUE_DEFAULT = 0,
    DOTA_ORDER_QUEUE_NEVER = 1,
    DOTA_ORDER_QUEUE_ALWAYS = 2,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ClickBehaviors = CLICK_BEHAVIORS;

declare enum CLICK_BEHAVIORS {
    DOTA_CLICK_BEHAVIOR_NONE = 0,
    DOTA_CLICK_BEHAVIOR_MOVE = 1,
    DOTA_CLICK_BEHAVIOR_ATTACK = 2,
    DOTA_CLICK_BEHAVIOR_CAST = 3,
    DOTA_CLICK_BEHAVIOR_DROP_ITEM = 4,
    DOTA_CLICK_BEHAVIOR_DROP_SHOP_ITEM = 5,
    DOTA_CLICK_BEHAVIOR_DRAG = 6,
    DOTA_CLICK_BEHAVIOR_LEARN_ABILITY = 7,
    DOTA_CLICK_BEHAVIOR_PATROL = 8,
    DOTA_CLICK_BEHAVIOR_VECTOR_CAST = 9,
    DOTA_CLICK_BEHAVIOR_UNUSED = 10,
    DOTA_CLICK_BEHAVIOR_RADAR = 11,
    DOTA_CLICK_BEHAVIOR_LAST = 12,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type AbilityLearnResult = AbilityLearnResult_t;

declare enum AbilityLearnResult_t {
    ABILITY_CAN_BE_UPGRADED = 0,
    ABILITY_CANNOT_BE_UPGRADED_NOT_UPGRADABLE = 1,
    ABILITY_CANNOT_BE_UPGRADED_AT_MAX = 2,
    ABILITY_CANNOT_BE_UPGRADED_REQUIRES_LEVEL = 3,
    ABILITY_NOT_LEARNABLE = 4,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type KeybindCommand = DOTAKeybindCommand_t;

declare enum DOTAKeybindCommand_t {
    DOTA_KEYBIND_NONE = 0,
    DOTA_KEYBIND_FIRST = 1,
    DOTA_KEYBIND_CAMERA_UP = 1,
    DOTA_KEYBIND_CAMERA_DOWN = 2,
    DOTA_KEYBIND_CAMERA_LEFT = 3,
    DOTA_KEYBIND_CAMERA_RIGHT = 4,
    DOTA_KEYBIND_CAMERA_GRIP = 5,
    DOTA_KEYBIND_CAMERA_YAW_GRIP = 6,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_1 = 7,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_2 = 8,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_3 = 9,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_4 = 10,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_5 = 11,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_6 = 12,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_7 = 13,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_8 = 14,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_9 = 15,
    DOTA_KEYBIND_CAMERA_SAVED_POSITION_10 = 16,
    DOTA_KEYBIND_HERO_ATTACK = 17,
    DOTA_KEYBIND_HERO_MOVE = 18,
    DOTA_KEYBIND_HERO_MOVE_DIRECTION = 19,
    DOTA_KEYBIND_PATROL = 20,
    DOTA_KEYBIND_HERO_STOP = 21,
    DOTA_KEYBIND_HERO_HOLD = 22,
    DOTA_KEYBIND_HERO_SELECT = 23,
    DOTA_KEYBIND_COURIER_SELECT = 24,
    DOTA_KEYBIND_COURIER_DELIVER = 25,
    DOTA_KEYBIND_COURIER_BURST = 26,
    DOTA_KEYBIND_COURIER_SHIELD = 27,
    DOTA_KEYBIND_PAUSE = 28,
    DOTA_SELECT_ALL = 29,
    DOTA_SELECT_ALL_OTHERS = 30,
    DOTA_RECENT_EVENT = 31,
    DOTA_KEYBIND_CHAT_TEAM = 32,
    DOTA_KEYBIND_CHAT_GLOBAL = 33,
    DOTA_KEYBIND_CHAT_TEAM2 = 34,
    DOTA_KEYBIND_CHAT_GLOBAL2 = 35,
    DOTA_KEYBIND_CHAT_VOICE_PARTY = 36,
    DOTA_KEYBIND_CHAT_VOICE_TEAM = 37,
    DOTA_KEYBIND_CHAT_WHEEL = 38,
    DOTA_KEYBIND_CHAT_WHEEL2 = 39,
    DOTA_KEYBIND_CHAT_WHEEL_CARE = 40,
    DOTA_KEYBIND_CHAT_WHEEL_BACK = 41,
    DOTA_KEYBIND_CHAT_WHEEL_NEED_WARDS = 42,
    DOTA_KEYBIND_CHAT_WHEEL_STUN = 43,
    DOTA_KEYBIND_CHAT_WHEEL_HELP = 44,
    DOTA_KEYBIND_CHAT_WHEEL_GET_PUSH = 45,
    DOTA_KEYBIND_CHAT_WHEEL_GOOD_JOB = 46,
    DOTA_KEYBIND_CHAT_WHEEL_MISSING = 47,
    DOTA_KEYBIND_CHAT_WHEEL_MISSING_TOP = 48,
    DOTA_KEYBIND_CHAT_WHEEL_MISSING_MIDDLE = 49,
    DOTA_KEYBIND_CHAT_WHEEL_MISSING_BOTTOM = 50,
    DOTA_KEYBIND_HERO_CHAT_WHEEL = 51,
    DOTA_KEYBIND_SPRAY_WHEEL = 52,
    DOTA_KEYBIND_ABILITY_PRIMARY1 = 53,
    DOTA_KEYBIND_ABILITY_PRIMARY2 = 54,
    DOTA_KEYBIND_ABILITY_PRIMARY3 = 55,
    DOTA_KEYBIND_ABILITY_SECONDARY1 = 56,
    DOTA_KEYBIND_ABILITY_SECONDARY2 = 57,
    DOTA_KEYBIND_ABILITY_ULTIMATE = 58,
    DOTA_KEYBIND_TALENT_UPGRADE_LEFT = 59,
    DOTA_KEYBIND_TALENT_UPGRADE_RIGHT = 60,
    DOTA_KEYBIND_TALENT_UPGRADE_ATTRIBUTE = 61,
    DOTA_KEYBIND_NEUTRAL_ITEM_SELECT1 = 62,
    DOTA_KEYBIND_NEUTRAL_ITEM_SELECT2 = 63,
    DOTA_KEYBIND_NEUTRAL_ITEM_SELECT3 = 64,
    DOTA_KEYBIND_NEUTRAL_ITEM_SELECT4 = 65,
    DOTA_KEYBIND_NEUTRAL_ITEM_SELECT5 = 66,
    DOTA_KEYBIND_ABILITY_PRIMARY1_QUICKCAST = 67,
    DOTA_KEYBIND_ABILITY_PRIMARY2_QUICKCAST = 68,
    DOTA_KEYBIND_ABILITY_PRIMARY3_QUICKCAST = 69,
    DOTA_KEYBIND_ABILITY_SECONDARY1_QUICKCAST = 70,
    DOTA_KEYBIND_ABILITY_SECONDARY2_QUICKCAST = 71,
    DOTA_KEYBIND_ABILITY_ULTIMATE_QUICKCAST = 72,
    DOTA_KEYBIND_ABILITY_PRIMARY1_EXPLICIT_AUTOCAST = 73,
    DOTA_KEYBIND_ABILITY_PRIMARY2_EXPLICIT_AUTOCAST = 74,
    DOTA_KEYBIND_ABILITY_PRIMARY3_EXPLICIT_AUTOCAST = 75,
    DOTA_KEYBIND_ABILITY_SECONDARY1_EXPLICIT_AUTOCAST = 76,
    DOTA_KEYBIND_ABILITY_SECONDARY2_EXPLICIT_AUTOCAST = 77,
    DOTA_KEYBIND_ABILITY_ULTIMATE_EXPLICIT_AUTOCAST = 78,
    DOTA_KEYBIND_ABILITY_PRIMARY1_QUICKCAST_AUTOCAST = 79,
    DOTA_KEYBIND_ABILITY_PRIMARY2_QUICKCAST_AUTOCAST = 80,
    DOTA_KEYBIND_ABILITY_PRIMARY3_QUICKCAST_AUTOCAST = 81,
    DOTA_KEYBIND_ABILITY_SECONDARY1_QUICKCAST_AUTOCAST = 82,
    DOTA_KEYBIND_ABILITY_SECONDARY2_QUICKCAST_AUTOCAST = 83,
    DOTA_KEYBIND_ABILITY_ULTIMATE_QUICKCAST_AUTOCAST = 84,
    DOTA_KEYBIND_ABILITY_PRIMARY1_AUTOMATIC_AUTOCAST = 85,
    DOTA_KEYBIND_ABILITY_PRIMARY2_AUTOMATIC_AUTOCAST = 86,
    DOTA_KEYBIND_ABILITY_PRIMARY3_AUTOMATIC_AUTOCAST = 87,
    DOTA_KEYBIND_ABILITY_SECONDARY1_AUTOMATIC_AUTOCAST = 88,
    DOTA_KEYBIND_ABILITY_SECONDARY2_AUTOMATIC_AUTOCAST = 89,
    DOTA_KEYBIND_ABILITY_ULTIMATE_AUTOMATIC_AUTOCAST = 90,
    DOTA_KEYBIND_INVENTORY1 = 91,
    DOTA_KEYBIND_INVENTORY2 = 92,
    DOTA_KEYBIND_INVENTORY3 = 93,
    DOTA_KEYBIND_INVENTORY4 = 94,
    DOTA_KEYBIND_INVENTORY5 = 95,
    DOTA_KEYBIND_INVENTORY6 = 96,
    DOTA_KEYBIND_INVENTORYTP = 97,
    DOTA_KEYBIND_INVENTORYNEUTRAL = 98,
    DOTA_KEYBIND_INVENTORY1_QUICKCAST = 99,
    DOTA_KEYBIND_INVENTORY2_QUICKCAST = 100,
    DOTA_KEYBIND_INVENTORY3_QUICKCAST = 101,
    DOTA_KEYBIND_INVENTORY4_QUICKCAST = 102,
    DOTA_KEYBIND_INVENTORY5_QUICKCAST = 103,
    DOTA_KEYBIND_INVENTORY6_QUICKCAST = 104,
    DOTA_KEYBIND_INVENTORYTP_QUICKCAST = 105,
    DOTA_KEYBIND_INVENTORYNEUTRAL_QUICKCAST = 106,
    DOTA_KEYBIND_INVENTORY1_AUTOCAST = 107,
    DOTA_KEYBIND_INVENTORY2_AUTOCAST = 108,
    DOTA_KEYBIND_INVENTORY3_AUTOCAST = 109,
    DOTA_KEYBIND_INVENTORY4_AUTOCAST = 110,
    DOTA_KEYBIND_INVENTORY5_AUTOCAST = 111,
    DOTA_KEYBIND_INVENTORY6_AUTOCAST = 112,
    DOTA_KEYBIND_INVENTORYTP_AUTOCAST = 113,
    DOTA_KEYBIND_INVENTORYNEUTRAL_AUTOCAST = 114,
    DOTA_KEYBIND_INVENTORY1_QUICKAUTOCAST = 115,
    DOTA_KEYBIND_INVENTORY2_QUICKAUTOCAST = 116,
    DOTA_KEYBIND_INVENTORY3_QUICKAUTOCAST = 117,
    DOTA_KEYBIND_INVENTORY4_QUICKAUTOCAST = 118,
    DOTA_KEYBIND_INVENTORY5_QUICKAUTOCAST = 119,
    DOTA_KEYBIND_INVENTORY6_QUICKAUTOCAST = 120,
    DOTA_KEYBIND_INVENTORYTP_QUICKAUTOCAST = 121,
    DOTA_KEYBIND_INVENTORYNEUTRAL_QUICKAUTOCAST = 122,
    DOTA_KEYBIND_CONTROL_GROUP1 = 123,
    DOTA_KEYBIND_CONTROL_GROUP2 = 124,
    DOTA_KEYBIND_CONTROL_GROUP3 = 125,
    DOTA_KEYBIND_CONTROL_GROUP4 = 126,
    DOTA_KEYBIND_CONTROL_GROUP5 = 127,
    DOTA_KEYBIND_CONTROL_GROUP6 = 128,
    DOTA_KEYBIND_CONTROL_GROUP7 = 129,
    DOTA_KEYBIND_CONTROL_GROUP8 = 130,
    DOTA_KEYBIND_CONTROL_GROUP9 = 131,
    DOTA_KEYBIND_CONTROL_GROUP10 = 132,
    DOTA_KEYBIND_CONTROL_GROUPCYCLE = 133,
    DOTA_KEYBIND_SELECT_ALLY1 = 134,
    DOTA_KEYBIND_SELECT_ALLY2 = 135,
    DOTA_KEYBIND_SELECT_ALLY3 = 136,
    DOTA_KEYBIND_SELECT_ALLY4 = 137,
    DOTA_KEYBIND_SELECT_ALLY5 = 138,
    DOTA_KEYBIND_SHOP_TOGGLE = 139,
    DOTA_KEYBIND_SCOREBOARD_TOGGLE = 140,
    DOTA_KEYBIND_COMBATLOG_TOGGLE = 141,
    DOTA_KEYBIND_SCREENSHOT = 142,
    DOTA_KEYBIND_ESCAPE = 143,
    DOTA_KEYBIND_CONSOLE = 144,
    DOTA_KEYBIND_DEATH_SUMMARY = 145,
    DOTA_KEYBIND_LEARN_ABILITIES = 146,
    DOTA_KEYBIND_LEARN_STATS = 147,
    DOTA_KEYBIND_ACTIVATE_GLYPH = 148,
    DOTA_KEYBIND_ACTIVATE_RADAR = 149,
    DOTA_KEYBIND_PURCHASE_QUICKBUY = 150,
    DOTA_KEYBIND_PURCHASE_STICKY = 151,
    DOTA_KEYBIND_TOGGLE_BUYBACK_PROTECTION = 152,
    DOTA_KEYBIND_GRAB_STASH_ITEMS = 153,
    DOTA_KEYBIND_TOGGLE_AUTOATTACK = 154,
    DOTA_KEYBIND_TOGGLE_OVERLAYMAP = 155,
    DOTA_KEYBIND_OVERLAYMAP_INPUTKEY = 156,
    DOTA_KEYBIND_FILTER_ENEMY = 157,
    DOTA_KEYBIND_FILTER_ALLY = 158,
    DOTA_KEYBIND_FILTER_HERO = 159,
    DOTA_KEYBIND_FILTER_NONHERO = 160,
    DOTA_KEYBIND_TAUNT = 161,
    DOTA_KEYBIND_SHOP_CONSUMABLES = 162,
    DOTA_KEYBIND_SHOP_ATTRIBUTES = 163,
    DOTA_KEYBIND_SHOP_ARMAMENTS = 164,
    DOTA_KEYBIND_SHOP_ARCANE = 165,
    DOTA_KEYBIND_SHOP_BASICS = 166,
    DOTA_KEYBIND_SHOP_SUPPORT = 167,
    DOTA_KEYBIND_SHOP_CASTER = 168,
    DOTA_KEYBIND_SHOP_WEAPONS = 169,
    DOTA_KEYBIND_SHOP_ARMOR = 170,
    DOTA_KEYBIND_SHOP_ARTIFACTS = 171,
    DOTA_KEYBIND_SHOP_SIDE_PAGE_1 = 172,
    DOTA_KEYBIND_SHOP_SIDE_PAGE_2 = 173,
    DOTA_KEYBIND_SHOP_SECRET = 174,
    DOTA_KEYBIND_SHOP_SEARCHBOX = 175,
    DOTA_KEYBIND_SHOP_SLOT_1 = 176,
    DOTA_KEYBIND_SHOP_SLOT_2 = 177,
    DOTA_KEYBIND_SHOP_SLOT_3 = 178,
    DOTA_KEYBIND_SHOP_SLOT_4 = 179,
    DOTA_KEYBIND_SHOP_SLOT_5 = 180,
    DOTA_KEYBIND_SHOP_SLOT_6 = 181,
    DOTA_KEYBIND_SHOP_SLOT_7 = 182,
    DOTA_KEYBIND_SHOP_SLOT_8 = 183,
    DOTA_KEYBIND_SHOP_SLOT_9 = 184,
    DOTA_KEYBIND_SHOP_SLOT_10 = 185,
    DOTA_KEYBIND_SHOP_SLOT_11 = 186,
    DOTA_KEYBIND_SHOP_SLOT_12 = 187,
    DOTA_KEYBIND_SHOP_SLOT_13 = 188,
    DOTA_KEYBIND_SHOP_SLOT_14 = 189,
    DOTA_KEYBIND_SPEC_CAMERA_UP = 190,
    DOTA_KEYBIND_SPEC_CAMERA_DOWN = 191,
    DOTA_KEYBIND_SPEC_CAMERA_LEFT = 192,
    DOTA_KEYBIND_SPEC_CAMERA_RIGHT = 193,
    DOTA_KEYBIND_SPEC_CAMERA_GRIP = 194,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_1 = 195,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_2 = 196,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_3 = 197,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_4 = 198,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_5 = 199,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_6 = 200,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_7 = 201,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_8 = 202,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_9 = 203,
    DOTA_KEYBIND_SPEC_CAMERA_SAVED_POSITION_10 = 204,
    DOTA_KEYBIND_SPEC_UNIT_SELECT = 205,
    DOTA_KEYBIND_SPEC_HERO_SELECT = 206,
    DOTA_KEYBIND_SPEC_PAUSE = 207,
    DOTA_KEYBIND_SPEC_CHAT = 208,
    DOTA_KEYBIND_SPEC_SCOREBOARD = 209,
    DOTA_KEYBIND_SPEC_INCREASE_REPLAY_SPEED = 210,
    DOTA_KEYBIND_SPEC_DECREASE_REPLAY_SPEED = 211,
    DOTA_KEYBIND_SPEC_STATS_ITEM = 212,
    DOTA_KEYBIND_SPEC_STATS_GOLD = 213,
    DOTA_KEYBIND_SPEC_STATS_XP = 214,
    DOTA_KEYBIND_SPEC_STATS_FANTASY = 215,
    DOTA_KEYBIND_SPEC_STATS_WINCHANCE = 216,
    DOTA_KEYBIND_SPEC_FOW_TOGGLEBOTH = 217,
    DOTA_KEYBIND_SPEC_FOW_TOGGLERADIENT = 218,
    DOTA_KEYBIND_SPEC_FOW_TOGGLEDIRE = 219,
    DOTA_KEYBIND_SPEC_OPEN_BROADCASTER_MENU = 220,
    DOTA_KEYBIND_SPEC_DROPDOWN_KDA = 221,
    DOTA_KEYBIND_SPEC_DROPDOWN_LASTHITS_DENIES = 222,
    DOTA_KEYBIND_SPEC_DROPDOWN_LEVEL = 223,
    DOTA_KEYBIND_SPEC_DROPDOWN_XP_PER_MIN = 224,
    DOTA_KEYBIND_SPEC_DROPDOWN_GOLD = 225,
    DOTA_KEYBIND_SPEC_DROPDOWN_TOTALGOLD = 226,
    DOTA_KEYBIND_SPEC_DROPDOWN_GOLD_PER_MIN = 227,
    DOTA_KEYBIND_SPEC_DROPDOWN_BUYBACK = 228,
    DOTA_KEYBIND_SPEC_DROPDOWN_NETWORTH = 229,
    DOTA_KEYBIND_SPEC_DROPDOWN_FANTASY = 230,
    DOTA_KEYBIND_SPEC_DROPDOWN_SORT = 231,
    DOTA_KEYBIND_SPEC_DROPDOWN_CLOSE = 232,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_1 = 233,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_2 = 234,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_3 = 235,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_4 = 236,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_5 = 237,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_6 = 238,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_7 = 239,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_8 = 240,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_9 = 241,
    DOTA_KEYBIND_SPEC_FOCUS_PLAYER_10 = 242,
    DOTA_KEYBIND_SPEC_COACH_VIEWTOGGLE = 243,
    DOTA_KEYBIND_INSPECTHEROINWORLD = 244,
    DOTA_KEYBIND_CAMERA_ZOOM_IN = 245,
    DOTA_KEYBIND_CAMERA_ZOOM_OUT = 246,
    DOTA_KEYBIND_CONTROL_GROUPCYCLEPREV = 247,
    DOTA_KEYBIND_DOTA_ALT = 248,
    DOTA_KEYBIND_DOTA_ALTERNATIVE_CAST_SWITCH = 249,
    DOTA_KEYBIND_COUNT = 250,
}

/**
 * @deprecated Normalized enum name. Defined only for library compatibility.
 */
type ShopType = DOTA_SHOP_TYPE;

declare enum DOTA_SHOP_TYPE {
    DOTA_SHOP_HOME = 0,
    DOTA_SHOP_SIDE = 1,
    DOTA_SHOP_SECRET = 2,
    DOTA_SHOP_GROUND = 3,
    DOTA_SHOP_SIDE2 = 4,
    DOTA_SHOP_SECRET2 = 5,
    DOTA_SHOP_CUSTOM = 6,
    DOTA_SHOP_NEUTRALS = 7,
    DOTA_SHOP_NONE = 8,
}
